### ISSUE TITLE
summary on the common component

### ISSUE THREAD

**Issue by nitescua** [rid00z/FreshMvvm#1]
Can you please do a little write up summarizing the common components \ features FreshMvvm has like navigation, property changed support, navigation, DI

**Comment by rid00z** [comment]
Hi, have you taken a look at the ReadMe file? It's fairly detailed. Or is there something else you would like?

**Comment by nitescua** [comment]
Hi Micheal,

I saw that, nice write up, I was just thinking it would be helpful for anyone who's checking out for first time to see a small list with all features, basically a TL;DR  :)
Something like:

"Common features:
Navigation - page navigation between pages by view-models
DI - dependency injection support"

**Comment by rid00z** [comment]
Ok thanks.
