### ISSUE TITLE
Implement RaiseAllPropertiesChanged on FreshBasePageModel

### ISSUE THREAD

**Issue by C0D3Name** [rid00z/FreshMvvm#100]
I know FreshMvvm was created with Fody in mind as the primary mechanism for invoking property changed, but as a fallback, there is the ability to use the RaisePropertyChanged method on FreshBasePageModel.

Sometimes it is advantageous to have the ability to invoke PropertyChanged with no parameters, which raises the PropertyChanged event for all public properties in a Page Model.  Currently there is no immediate means of doing this on FreshBasePageModel.  

**Any thoughts on adding the following method to FreshBasePageModel?**

```csharp
protected void RaiseAllPropertiesChanged()
{
    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(string.Empty));
}
```
**RaisePropertyChanged can also be rewritten as follows for C# 6 (although this is just semantics)**

**Before**

```csharp
protected void RaisePropertyChanged ([CallerMemberName] string propertyName = null)
{
    var handler = PropertyChanged;
    if (handler != null) {
        handler (this, new PropertyChangedEventArgs (propertyName));
    }
}
```

**After**
```csharp
protected void RaisePropertyChanged ([CallerMemberName] string propertyName = null)
{
    PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
}
```

**Comment by oddbear** [comment]
Can't you just do something like this:
```csharp
RaisePropertyChanged(string.Empty);
//or:
PropertyChanged += (sender, e) =>
    if(e.PropertyName != string.Empty)
        RaisePropertyChanged(string.Empty);
```

Forcing a <code>RaisePropertyChanged(string.Empty);</code> actually saved the day. I have some strange bug that even with BeginInvokeOnMainThread, nothing was updated in the UI (after a await from a web call).

**Comment by C0D3Name** [comment]
Using  `RaisePropertyChanged(string.empty);` would definitely work. I'm not sure why I didn't see that before..
