### ISSUE TITLE
Switching Navigation Stacks causes Nullreference error

### ISSUE THREAD

**Issue by Robatjazi** [rid00z/FreshMvvm#106]
I have registered 2 navigation. Login and Main.
After authentication on login page which is a WebView with and Identity Server link, I try to switch to Main navigation in LoginPageModel.cs :
CoreMethods.SwitchOutRootNavigation(App.MainNavigationContainer);

If I just push a page(await Navigation.PushAsync(new MyPage());) instead of switching navigation, it works (but obviously just one page will b loaded and not the whole navigation) 

I am getting following error:

Unhandled Exception:

System.NullReferenceException: Object reference not set to an instance of an object.

09-22 12:02:35.802 D/Mono    ( 5078): DllImport attempting to load: '/system/lib/liblog.so'.
09-22 12:02:35.802 D/Mono    ( 5078): DllImport loaded library '/system/lib/liblog.so'.
09-22 12:02:35.802 D/Mono    ( 5078): DllImport searching in: '/system/lib/liblog.so' ('/system/lib/liblog.so').
09-22 12:02:35.802 D/Mono    ( 5078): Searching for '__android_log_print'.
09-22 12:02:35.802 D/Mono    ( 5078): Probing '__android_log_print'.
09-22 12:02:35.802 D/Mono    ( 5078): Found as '__android_log_print'.
09-22 12:02:35.803 I/MonoDroid( 5078): UNHANDLED EXCEPTION:
09-22 12:02:35.803 I/MonoDroid( 5078): System.NullReferenceException: Object reference not set to an instance of an object.
09-22 12:02:35.803 I/MonoDroid( 5078):   at Xamarin.Forms.Platform.Android.WebViewRenderer.UpdateCanGoBackForward () [0x0000c] in <filename unknown>:0 
09-22 12:02:35.803 I/MonoDroid( 5078):   at Xamarin.Forms.Platform.Android.WebViewRenderer+WebClient.ShouldOverrideUrlLoading (Android.Webkit.WebView view, System.String url) [0x0003b] in <filename unknown>:0 
09-22 12:02:35.804 I/MonoDroid( 5078):   at Android.Webkit.WebViewClient.n_ShouldOverrideUrlLoading_Landroid_webkit_WebView_Ljava_lang_String_ (IntPtr jnienv, IntPtr native__this, IntPtr native_view, IntPtr native_url) [0x00019] in /Users/builder/data/lanes/3415/7db2aac3/source/monodroid/src/Mono.Android/platforms/android-23/src/generated/Android.Webkit.WebViewClient.cs:766 
09-22 12:02:35.804 I/MonoDroid( 5078):   at (wrapper dynamic-method) System.Object:0b921996-a936-4597-9820-c5f42e41629f (intptr,intptr,intptr,intptr)
09-22 12:02:35.806 W/art     ( 5078): JNI RegisterNativeMethods: attempt to register 0 native methods for android.runtime.JavaProxyThrowable
09-22 12:02:35.809 D/Mono    ( 5078): DllImport searching in: '__Internal' ('(null)').
09-22 12:02:35.809 D/Mono    ( 5078): Searching for 'java_interop_jnienv_throw'.
09-22 12:02:35.809 D/Mono    ( 5078): Probing 'java_interop_jnienv_throw'.
09-22 12:02:35.809 D/Mono    ( 5078): Found as 'java_interop_jnienv_throw'.
An unhandled exception occured.

Any idea why it is happening?

**Comment by rid00z** [comment]
What version of Xamarin.Forms are you using? I think it might be a issue with Forms.

**Comment by Robatjazi** [comment]
I fixed the issue by updating to Xamarin Form v2.3. I was using v2.0.
It seems a bug on v2.0

Thanks.

**Comment by escamoteur** [comment]
I think then this could be closed :-)
