### ISSUE TITLE
Howto iterate over all current PageModels

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [rid00z/FreshMvvm#118]
Is there a way to iterate over all PageModels that are currently in any Navigation Stack?

I am changing a global property (the system language) and I want all of them to emit a PropertyChanged event.

**Comment by poimis** [comment]
@RudolfVonKrugstein Would `CurrentPage.Navigation.NavigationStack` be of any help?

**Comment by RudolfVonKrugstein** [comment]
Yes, thanks!
