### ISSUE TITLE
Best practices for Unit Test with FreshMvvm?

### ISSUE THREAD

**Issue by jamesatgithub** [rid00z/FreshMvvm#125]
In a unit test for a view model, I used below code to register a mock data service, instantiate the view model which has constructor injection of the data service and run the command on this view model,

```
FreshIOC.Container.Register<IFeedService, MockFeedService>();
DetailsPageModel pageModel = FreshIOC.Container.Resolve<DetailsPageModel>();
pageModel.SendCommand.Execute(null);
...
```
but in the command I used CoreMethods which is null in the unit test env, is this the correct way to write unit test for view model? Or any steps I have missed?

Thanks

**Comment by jamesatgithub** [comment]
I found an example in which using Moq for the CoreMethods.

**Comment by straiser** [comment]
@jamesatgithub 
How did you do that? Could you give an example?

**Comment by jamesatgithub** [comment]
@straiser  https://github.com/rid00z/FreshMvvmCustomNavSample/blob/master/FreshMvvmCustomNavSample.Tests/Quotes/QuotePageModelTests.cs
