### ISSUE TITLE
PageModels from different assemblies?

### ISSUE THREAD

**Issue by hxhieu** [rid00z/FreshMvvm#130]
Hi there,

I think it'd better to separate the models for re-usability.
Did I miss something here but I couldn't get it to work if putting the page models on another assembly?

Thanks,
H

**Comment by rid00z** [comment]
You need to use a custom pagemodel mapper in this case.

**Comment by hxhieu** [comment]
@rid00z Thanks, but I am pretty new to FreshMvvm - just an hour into it. So is there any example? or just a few lines snippet here would help. Cheers.

**Comment by hxhieu** [comment]
Closing this now as I have managed to resolve this by looking at the FreshPageModelResolver code. Cheers
