### ISSUE TITLE
Unable to compile FreshMvvm sample

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [rid00z/FreshMvvm#141]
Hey,
I cloned this project and opened it in visual studio 2015. When I try to compile it, I get:

```
Error	CS0103	The name 'InitializeComponent' does not exist in the current context	FreshMvvmSampleApp	C:\Users\nathan\projects\external\FreshMvvm\samples\FreshMvvmSampleApp\FreshMvvmSampleApp\Pages\ContactListPage.xaml.cs	12	Active
```

Any Idea on how to fix this?

**Comment by WiteCastle** [comment]
Kind of hard to tell without much more information. But have you tried deleting the packages folder and then rebuilding the project? Also, if theres any output in the build window could you paste that here?

**Comment by RudolfVonKrugstein** [comment]
Deleting the Debug/Release and packages Folder and restarting VS helped. Thanks!
