### ISSUE TITLE
FreshMvvm and full linking on Android doesnt work

### ISSUE THREAD

**Issue by EmilAlipiev** [rid00z/FreshMvvm#144]
Do you have any idea or tested how Freshmvvm working with Full linking on android? I am not able to make it work although I added FreshMvvm;FreshIOC as skip. any advice please?

**Comment by EmilAlipiev** [comment]
I created a totally empty page and page model by referencing to freshmvvm. It works if I link only sdk but it doesnt work if I link everything
it fails on the line saying "FreshTinyIoC.TinyIoCResolutionException: Resolve failed: TestPageModel"

` var page = FreshPageModelResolver.ResolvePageModel<TestPageModel>();`

I have already added "skip linking assemblies" as FreshMvvm;FreshMvvm.FreshIOC;FreshIOC
What is the solution here please?

**Comment by WiteCastle** [comment]
I'm sorry but I'm having trouble understanding what you mean by "full linking". Do you mean dependency injection? Where are you creating that page variable? Also, it would be helpful if you attached the sample project here so we can try to recreate your issue.

**Comment by EmilAlipiev** [comment]
SDK and User Assemblies I meant but I figured out the problem. adding Preserve attribute on each page and pagemodel solves the linking issue.
