### ISSUE TITLE
Doesn't support Light StatusBar on iOS

### ISSUE THREAD

**Issue by allenmoatallen** [rid00z/FreshMvvm#15]
Currently there is no way to modify the BarTextColor of the NavigationPage object inside the navigation containers. In Xamarin.Forms in order to have a light status bar for iOS, the BarTextColor must be set to White.

Is there any chance this can be added? Not sure the best way to do so or I would make a pull request. In my test I added a boolean to CreateContainerPage
```C#
protected virtual Page CreateContainerPage(Page page, bool isLight = false)
    {
        var nav = new NavigationPage(page);
        if (isLight)
        {
            nav.BarTextColor = Color.White;
        }
        return nav;
    }
```

**Comment by rid00z** [comment]
I thought the best way to do this would be to inherit the Page and override the CreateContainerPage method.

**Comment by allenmoatallen** [comment]
I will try that! I appreciate the feedback.

**Comment by allenmoatallen** [comment]
Just wanted to let you know that worked perfectly!
