### ISSUE TITLE
PageWasPopped event not fired sometimes

### ISSUE THREAD

**Issue by EmilAlipiev** [rid00z/FreshMvvm#155]
I am trying to understand PageWasPopped event. I implemented 2 different pagemodals which are both inheriting FreshBasePageModel and navigation to those pages are done like below
  await CoreMethods.PushPageModel<TestPageModel>(data:Test);

But on 1 page when I click back button (Soft or Hard), It always fires PageWasPopped  event. 
On other one it doesnt at all. I am comparing both pages but I cant figure what could be the reason.
Is there any known reason or a must in order to get PageWasPopped  event to be raised?

I assume that PageWasPopped  event is fired on Android only either of the back button is clicked. 
I am not using any Custom navigation

**Comment by WiteCastle** [comment]
Can you post a sample with the issue?

**Comment by EmilAlipiev** [comment]
It looks like this functions is not working anymore at all. previous versions were working but not even triggered any longer.

**Comment by EmilAlipiev** [comment]
I found the reason. if you override ViewIsAppearing method, Pagewaspopped never gets called. you need to add in your override method these lines

  if (!_alreadyAttached)
                AttachPageWasPoppedEvent();
