### ISSUE TITLE
[Question] Any issues with Forms 2.3.4?

### ISSUE THREAD

**Issue by RocketPop** [rid00z/FreshMvvm#156]
Hi - I don't see much activity since Aug 2016 - does FreshMVVM work well with the new Forms 2.3.4 release? Any breaking or quirky changes?  We are spinning up a new project and I would like to use FreshMVVM again!

**Comment by Dids** [comment]
I'm using it in production with the latest XF, and so far no (new) issues.

**Comment by jfversluis** [comment]
I'm with @Dids using this extensively and no problems at all.

**Comment by RocketPop** [comment]
Thanks everyone!
