### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by JoshuaNovak919** [rid00z/FreshMvvm#157]
Is FreshMvvm still being maintained or do we need to start looking elsewhere? It's been over 8 months since the last update and Xamarin has been updated a lot since then.

**Comment by jfversluis** [comment]
Are you basing this on just the fact that it hasn't been updated for 8 months?
I'm still using this in almost every project and didn't run into any problems, not even with the latest Xamarin bits. So, are you missing any features? Are you running into any problems? Or does it just need to be updated to that it is updated?

**Comment by rid00z** [comment]
We're still using in production and new projects, it's solid and doesn't have issues so we don't need to release. 

We have some features planned but they are nice to have rather than immediate issues.

**Comment by JoshuaNovak919** [comment]
I was just curious because there are 59 outstanding issues and there haven't been updates in 8 months. Usually when there are that many issues and such a long time without updates the project is dead. I was just trying to see if I need to look into new frameworks for my next project or if i'm still safe using this one.
