### ISSUE TITLE
 FreshTabbedFONavigationContainer Title Space

### ISSUE THREAD

**Issue by danielc103** [rid00z/FreshMvvm#158]
More of a question possibly. 

Wondering how to remove the title bar above the tabs.  This seems to only be generated for the TabbedFO Container.  

I've tried changing the theme in android to remove navigation or title bar to no avail.

<img width="460" alt="screen shot 2017-04-23 at 3 57 00 pm" src="https://cloud.githubusercontent.com/assets/9359287/25316950/c954cb7c-283d-11e7-9b1b-d2539504b753.png">

**Comment by rid00z** [comment]
You can hide the NavigationBar using the standards Xamarin.Forms method. 

NavigationPage.SetHasNavigationBar(this, false);
