### ISSUE TITLE
Enable/disable tabs in code?

### ISSUE THREAD

**Issue by MBrekhof** [rid00z/FreshMvvm#17]
I would like to be able to enable/disable one or more tabs (using tabbed navigation) based on certain conditions during run-ime. Is this possible (hiding/showing would be a good alternative).

**Comment by rid00z** [comment]
In this case you'll need to implement custom navigation!

http://www.michaelridland.com/xamarin/implementing-freshmvvm-mvvm-xamarin-forms/
