### ISSUE TITLE
Masterdetail Navigations as async? 

### ISSUE THREAD

**Issue by EmilAlipiev** [rid00z/FreshMvvm#172]
It seems like masterdetail Navigations are sync. Is there a way to async them so i can Display loading Progress asyncronously. Current when i click an item from master Detail it freezes for 3 secs if page needs 3 secs to load.

**Comment by rid00z** [comment]
I would suggest that you first do the navigation, load the UI controls so that the user can see it. Then  begin the network request and fill out the data.

**Comment by EmilAlipiev** [comment]
I have the loading data inside ViewIsAppearing function which is async and UI should be already there. Do you mean that?
