### ISSUE TITLE
Access CoreMethods from ContentView

### ISSUE THREAD

**Issue by FatMooseHenry** [rid00z/FreshMvvm#179]
I am not completely sure on how FreshMvvm fits into custom controls, and I hope you can provide some "best practices" on this.
I have a custom control in a ContentView that needs to display the ActionSheet. For this I was going to use:
CoreMethods.DisplayActionSheet
but that is only available on the models. 
Is there another way than traversing the Parent property until I get to the page, or do FreshMvvm has a solution for this?

**Comment by EmilAlipiev** [comment]
You can do that in yout ViewModel, Freshmvvm binds your View and ViewModel, it has nothing to do with the contentview. CoreMethods only work within ViewModel if FreshBasePageModel is implemented. For that you need to achieve this with Binding from your CustomControl to your Viewmodel Property.

**Comment by FatMooseHenry** [comment]
Ok, I ended up using Acr.UserDialogs which can be resolved through FreshIOC.
If other people have the same issue, one way to do it, is to get:
this.Parent.BindingContext until you get a FreshBasePageModel which you then can use

**Comment by marcoseraphin** [comment]
Hi FatMooseHenry,

I am using the Acr.UserDialogs with the Dependency Injection (constructor injection) implemented in FreshMVVM:

Register the Instance:

FreshIOC.Container.Register<IUserDialogs>(UserDialogs.Instance);

Than use in ViewModel using DI:

 public class PoliciesPageModel : FreshBasePageModel
	{

		IUserDialogs userdialogs;
		IPolicyService policyservice;

		public PoliciesPageModel(IUserDialogs userDialogs, IPolicyService policyService) 
		{
			userdialogs = userDialogs;
			policyservice = policyService;
......

await userdialogs.AlertAsync("Blabla...


Best

Marco
