### ISSUE TITLE
Tab contents not showing when using XAML

### ISSUE THREAD

**Issue by jfversluis** [rid00z/FreshMvvm#18]
Hi Michael,

I love my XAML so I tried to use FreshMvvm with a TabbedPage in XAML as well.
Mostly goes fine, but it won't show the actual content of the selected page. I'm probably doing something wrong, but I can't figure out what.

This is the XAML page I have.

```
<?xml version="1.0" encoding="utf-8" ?>
<TabbedPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="Kilomeeter.Pages.MainPage" ItemsSource="{Binding Pages}">
  <TabbedPage.ItemTemplate>
    <DataTemplate>
      <Page Title="{Binding Title}" Icon="{Binding Icon}" />
    </DataTemplate>
  </TabbedPage.ItemTemplate>
</TabbedPage>
```

And this is my PageModel:

```
public class MainPageModel : FreshBasePageModel
    {
        public ObservableCollection<object> Pages { get; set; }

        public Page SelectedPage { get; set; }

        public MainPageModel()
        {
            Pages = new ObservableCollection<object>
            {
                FreshPageModelResolver.ResolvePageModel<CarsOverviewPageModel>(),
                FreshPageModelResolver.ResolvePageModel<MapPageModel>()
            };
        }
    }
```

Nothing fancy.
I've tried setting the `SelectedPage` and the `CurrentPage` on the TabbedPage but nothing seems to show up. Just the tabs, which are selectable, but an empty screen.

Any thoughts?

**Comment by MBrekhof** [comment]
I'm not Michael but I noticed 'Kilomeeter' in the namespace, is that correct?

**Comment by jfversluis** [comment]
Yeah? That's the name of my project

**Comment by MBrekhof** [comment]
Ok, I would have expected 'Kilometer' and thought this could be a typo :-)

**Comment by rid00z** [comment]
Hi @jfversluis You didn't happen to have a sample app?

**Comment by jfversluis** [comment]
Not yet.. I'll try to provide you one today!

**Comment by jfversluis** [comment]
Here you go; https://github.com/jfversluis/FreshMvvmEmptyTab

Maybe I'm missing something..
Check the app.cs for a TODO that does work, but that means having to build my container page in code which I don't want.

**Comment by escamoteur** [comment]
Hi @jfversluis did you get this issue solved? I'm still evaluating which framework to use.

**Comment by jfversluis** [comment]
Unfortunately not. Still using the default containers or creating a custom one in code.

**Comment by rid00z** [comment]
I understand the want to do this but I'm not sure how much extra this gives as it can be done in code which will have extra features like the DI.
