### ISSUE TITLE
PageModelCoreMethods.PushPageModel(Type pageModelType, object data, ...) not included in IPageModelCoreMethods 

### ISSUE THREAD

**Issue by cimicdk** [rid00z/FreshMvvm#181]
The method:
public Task PushPageModel(Type pageModelType, object data, bool modal = false, bool animate = true)
in PageModelCoreMethods is not added to the interface IPageModelCoreMethods

Properly not intented :)

**Comment by straiser** [comment]
up, PR for this is waiting long time

**Comment by rid00z** [comment]
Apologies, I've just merged this.
