### ISSUE TITLE
Pages not garbage collected and therefore leaking (Android).

### ISSUE THREAD

**Issue by james-lavery** [rid00z/FreshMvvm#183]
When investigating memory leaks in our application, I think I have uncovered a leak concerning pages not being Garbage Collected after navigating back.

With a simple main BasicPage, from which we navigate to Basic2Page, and then press the back button to navigate back to BasicPage, I am seeing that Basic2Page is not being garbage collected. There are no Commands or other complications on Basic2Page.

I'm detecting the lack of garbage collection by taking a weak reference to Basic2Page in its constructor; latter it can be seen that the object has not been garbage collected.

[This GitHub repository ](https://github.com/MicrosecLtdUk/FormsLeakTest2)demonstrates the behaviour and has more notes.

Has anyone else seen this behaviour? This is potentially a fundamental problem for us as it means that our non-trivial app is leaking a lot!

Versions: FreshMvvm 2.2.0
Xamarin.Forms: 2.3.4.270

=== Visual Studio Community 2017 for Mac ===

Version 7.1.5 (build 2)
Installation UUID: 650b4c91-c7f5-4ee5-ad70-6f178f314906
Runtime:
	Mono 5.2.0.224 (d15-3/14f2c81) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)

	Package version: 502000224

=== NuGet ===

Version: 4.3.0.2418

=== .NET Core ===

Runtime: Not installed
SDK: Not installed
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.2.0/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.5.5
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 8.0 (11246)
Build 8A218a

=== Xamarin.Android ===

Version: 7.4.5.1 (Visual Studio Community)
Android SDK: /Users/jameslavery/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3   (API level 10)
		4.0.3 (API level 15)
		4.1   (API level 16)
		4.3   (API level 18)
		4.4   (API level 19)
		5.0   (API level 21)
		5.1   (API level 22)
		6.0   (API level 23)
		7.0   (API level 24)
		7.1   (API level 25)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 26.0.0
SDK Build Tools Version: 26.0.2

Java SDK: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin.iOS ===

Version: 11.0.0.0 (Visual Studio Community)
Hash: 152b654a
Branch: xcode9
Build date: 2017-09-15 02:25:56-0400

=== Xamarin Inspector ===

Version: 1.3.1
Hash: cbc48dd
Branch: 1.3-release
Build date: Thu, 21 Sep 2017 19:52:53 GMT
Client compatibility: 1

=== Xamarin.Mac ===

Version: 3.6.3.3 (Visual Studio Community)

=== Build Information ===

Release ID: 701050002
Git revision: 7afedcaef8e7542e70e3cf8f9bdb26938b8c0876
Build date: 2017-09-15 08:39:58-04
Xamarin addins: 3262aadf811a18c12eac6742532d052b0139a808
Build lane: monodevelop-lion-d15-3-xcode9

=== Operating System ===

Mac OS X 10.11.6
Darwin 15.6.0 Darwin Kernel Version 15.6.0
    Thu Jun 23 18:25:34 PDT 2016
    root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

Redth's Addins 1.0.9

**Comment by rid00z** [comment]
I've checked system for memory leaks before but I will look into it now again.

**Comment by james-lavery** [comment]
Thanks Michael,
I've just run up one of the stock Xamarin sample apps, and it doesn't exhibit the same retained page reference behaviour - so it does seem to be to do with FreshMvvm I'm afraid.

**Comment by james-lavery** [comment]
I've been doing some investigation, and think I have a solution to the Page leak.

I had to add a _Cleanup_ method to _PageModelCoreMethods.cs_:

```
public void Cleanup()
 {
    this._currentPage = null;
 }
```

and then add the following to _RaisePageWasPopped_ in _FreshBasePageMode.cs_:

```
CurrentPage = null;
this.CoreMethods.Cleanup();
```

This appears to stop the _Page_ leaking - it's now GC'd.

However, PageModels are still leaking. I think it's to do with the fact that the navPage.Popped event handler is not being unsubscribed. The code to do this is in _RaisePageWasPopped_ in _FreshBasePageModel.cs_:

```
var navPage = (this.CurrentPage.Parent as NavigationPage);
if (navPage != null)
    navPage.Popped -= HandleNavPagePopped;
```

However, at the point this is called, _this.CurrentPage.Parent_ is _null_, and therefore the event is not being unhooked. This will, I think, be leaving the PageModel referenced by the navPage via the handler and stopping the PageModel being GC'd

**Comment by james-lavery** [comment]
I think it _is_ the HandleNavPagePopped handler which is causing the PageModel to not be GC'd.

The problem for me is that the CurrentPage is being set to _null_ before _RaiseWasPopped_ is being called - I assume deep in the Navigation code, as I cannot see where this is being done. Therefore I've implemented the slightly inelegant (I think) solution below which works.

Added a private field:

`private NavigationPage CurrentPageNavigationPage = null;`

Amended _AttachPageWasPoppedEvent_:

```
public void AttachPageWasPoppedEvent()
{
    var navPage = (this.CurrentPage.Parent as NavigationPage);
    if (navPage != null)
    {
        CurrentPageNavigationPage = navPage;
        _alreadyAttached = true;
        navPage.Popped += HandleNavPagePopped;
    }
}
```

Amended the code in _RaisePageWasPopped_, relating to clearing the HandleNavPagePopped handler, to:

```
var navPage = (this.CurrentPage.Parent as NavigationPage);
if (navPage != null)
{
    navPage.Popped -= HandleNavPagePopped;
}
else if (CurrentPageNavigationPage != null)
{
    CurrentPageNavigationPage.Popped -= HandleNavPagePopped;
}

CurrentPageNavigationPage = null;
```

With the above changes, I now do not see PageModels remaining after calling GC.Collect() - so I think this fixes the PageModel leak.

However, there is probably a more elegant solution!

**Comment by rid00z** [comment]
Hi, I've reproduced this issue and come up with a solution I'm happy with. I can push the code up for you to take a look at and then I can do a release.

**Comment by jackjackson** [comment]
That's great Michael. Yes - please push! (we have an interest in this issue too)

**Comment by james-lavery** [comment]
Hi Michael,
Great - please push ASAP, I have a customer desperate for this fix.

Regards,

James

**Comment by rid00z** [comment]
Ok, this must have change with a Xamarin.Forms update. I will publish a new nuget.

**Comment by jackjackson** [comment]
Hi Michael,
How is this one going? Do you know when we can try the update. It will solve a whole load of problems for us.
J

**Comment by james-lavery** [comment]
Hi Michael,
Also a question on the resolution.

I've noticed in my fixing of it locally here that we probably need to clear the PreviousPageModel field in RaisePageWasPopped, to make doubly sure that we've got no lingering references to PageModels.

I've checked, and RaisePageWasPopped is called after PreviousPageModel.ReverseInit, so this is safe to do.

Of course, you may have got a more elegant solution than mine...

**Comment by rid00z** [comment]
I used Rx for weak subscriptions, take a look. - https://github.com/rid00z/FreshMvvm/tree/resolve-memory-issue

**Comment by james-lavery** [comment]
Hi Michael,
Thanks - that looks like an elegant solution to the event handler problem!

I found that I also needed to set CurrentPage (and PreviousPageModel) to null in RaisePageWasPopped, to ensure that Pages and PageModels are freed. Did you find this too, or do you think the solution is all with event handlers?

**Comment by EmilAlipiev** [comment]
and does this fix release already support net standard 1.4?

**Comment by jackjackson** [comment]
Michael
Are there any commits for this one?
J

**Comment by jackjackson** [comment]
...I see it: https://github.com/rid00z/FreshMvvm/tree/resolve-memory-issue

**Comment by rid00z** [comment]
This is published into nuget today.

**Comment by EmilAlipiev** [comment]
Hi @rid00z 

thank you for that update. quick question, now bunch of other libraries are also installed into forms project as shown below. What is the reason? is it because .net standard support is also pushed? 

![image](https://user-images.githubusercontent.com/10422347/31609798-e2bf5b0a-b275-11e7-9237-dd08e45d6eb7.png)

**Comment by james-lavery** [comment]
@EmilAlipiev I'm seeing this too, and probably as a result, am getting the error:

> /Users/jameslavery/Documents/P4/THI/Musterd/src/dev_JGL2/Musterd.Core.Droid/CSC: Error CS1703: Multiple assemblies with equivalent identity have been imported: '/Users/jameslavery/Documents/P4/THI/Musterd/src/dev_JGL2/packages/System.Runtime.InteropServices.WindowsRuntime.4.0.1/lib/netstandard1.3/System.Runtime.InteropServices.WindowsRuntime.dll' and '/Library/Frameworks/Mono.framework/External/xbuild-frameworks/MonoAndroid/v1.0/Facades/System.Runtime.InteropServices.WindowsRuntime.dll'. Remove one of the duplicate references. (CS1703) (Musterd.Core.Droid)

Any idea on the solution?

**Comment by EmilAlipiev** [comment]
It looks like for me update will not possible as well. one of the package complains about profile as I am using 259. I think that it is not fair us to force to use 111 profile for this very important update. 

![image](https://user-images.githubusercontent.com/10422347/31919192-033c09fa-b861-11e7-9208-96ca24211d2d.png)

**Comment by rid00z** [comment]
@EmilAlipiev This is not a requirement of FreshMvvm but because of the rx.net dependancy.

**Comment by EmilAlipiev** [comment]
I can understand it but can you Kindly explain why suddenly we need all these libraries to work with freshmvvm?

**Comment by james-lavery** [comment]
The solution which Michael implemented, to solve the memory leak, was elegant in terms of its implementation - it makes the event subscriptions weak so that they don't hold references to the classes implementing them.

He used the Rx package to implement this. The downside is that Rx has dependencies on all these other packages.

This is a classic case of using a useful feature of a package/framework, but having to bring in all the 'baggage' of the package.

This isn't a criticism of Michael's solution - but an explanation of why we're getting all these packages with this fix.

Now my 2 pence worth (or 2 cents if you're not in the UK).

My solution was as I described in an earlier post (sorry, quote markdown doesn't seem to be working here)

=====
Added a private field:

private NavigationPage CurrentPageNavigationPage = null;

Amended AttachPageWasPoppedEvent:

public void AttachPageWasPoppedEvent()
{
    var navPage = (this.CurrentPage.Parent as NavigationPage);
    if (navPage != null)
    {
        CurrentPageNavigationPage = navPage;
        _alreadyAttached = true;
        navPage.Popped += HandleNavPagePopped;
    }
}
Amended the code in RaisePageWasPopped, relating to clearing the HandleNavPagePopped handler, to:

var navPage = (this.CurrentPage.Parent as NavigationPage);
if (navPage != null)
{
    navPage.Popped -= HandleNavPagePopped;
}
else if (CurrentPageNavigationPage != null)
{
    CurrentPageNavigationPage.Popped -= HandleNavPagePopped;
}

CurrentPageNavigationPage = null;
===

With this solution, the memory leak is solved with no extra packages.

I have to admit I too would prefer this approach rather than using Rx and weak subscriptions with the associated extra packages. Changing profiles and/or having more packages just adds to the potential for 'package hell'.

**Comment by EmilAlipiev** [comment]
On the other hand above library InteropServices does support 259 profile but I guess latest version only, I am not sure. I have already installed it together with other library. But now i cant install older version. it is a conflict for me to use older version. Cant we please at least get latest version of it?

![image](https://user-images.githubusercontent.com/10422347/31996519-1cf51ab6-b989-11e7-8cd3-a445ba839fa7.png)

**Comment by EmilAlipiev** [comment]
Hi, 

I am coming back to this issue and I have feeling that this is not resolved yet. Dont you think that we should implement   IDisposable on FreshBasePageModel.. because it looks like that not only Pages but also PageModels are not disposed?
