### ISSUE TITLE
Forms version

### ISSUE THREAD

**Issue by MBrekhof** [rid00z/FreshMvvm#19]
Not sure if this is a general Xamarin Forms question/problem but: FreshMvvm when got through nuget has been build with Forms 1.4.... We are currently at Forms 1.5.1. This seemed to be no problem until we started getting errors about 'xamlctask compilation'
I resolved this by removing the FreshMvvm nuget package, build the FreshMvvm dll's using the zip from nuget and referencing the resulting Dll's in my project.
Any comments?

**Comment by rid00z** [comment]
This is just a Xamarin.Forms issue.
