### ISSUE TITLE
FileNotFoundException: Could not load assembly FreshMvvm when using FreshMvvm with .NET Standard library

### ISSUE THREAD

**Issue by kaitlynbrown** [rid00z/FreshMvvm#191]
I've created a Xamarin.Forms project which uses .Net Standard 1.4 for the main assembly instead of a PCL. After adding the FreshMvvm NuGet package, I see the following error when trying to build Android:

> Exception while loading assemblies: System.IO.FileNotFoundException: Could not load assembly 'FreshMvvm, Version=1.0.6508.20839, Culture=neutral, PublicKeyToken='. Perhaps it doesn't exist in the Mono for Android profile?

**Comment by michelmoorlag** [comment]
I have done the same with 1.4 and with 2.0 and both configurations are working without issues. Have you checked your dependencies?

**Comment by kaitlynbrown** [comment]
The issue was resolved after I installed FreshMVVM on my platform-specific projects. I had thought that it would only need to be installed in the shared project, but I guess I was wrong! Thank you for the help!
