### ISSUE TITLE
Version 2.2.3 failing on new project

### ISSUE THREAD

**Issue by hauteur** [rid00z/FreshMvvm#193]
I created a brand new Xamarin Forms project (.net standard) and included 2.2.3.  Everything builds fine, but when I call ResolvePageModel, I get an error:

System.IO.FileNotFoundException: Could not load file or assembly 'FreshMvvm, Version=1.0.6508.20839, Culture=neutral, PublicKeyToken=null' or one of its dependencies.

If I take out the ResolvePageModel call, the project runs fine.  Also, the page model does inherit from FreshBasePageModel, but there is no code in it.

**Comment by rid00z** [comment]
Do you have FreshMvvm references in your native projects?

-- 

[image: XAM-Consulting Pty Ltd] <http://www.xam-consulting.com/>

[image: Twitter]  <https://twitter.com/XAMConsulting>   [image: LinkedIn]
<https://www.linkedin.com/company-beta/5791295/>

Michael Ridland / Director / Xamarin & Microsoft MVP
michael@xam-consulting.com / 0404 865 350

XAM Consulting Pty. Limited.
Web | Cloud | Apps | Xamarin
210/29 Kiora Rd, Miranda NSW 2228
xam-consulting.com <http://www.xam-consulting.com/>

**Comment by hauteur** [comment]
Thank you for responding.  

I do not.  Should I?

**Comment by hauteur** [comment]
That allowed it to run.  Thank you.
