### ISSUE TITLE
Windows 10 Universal App Platform compatibility

### ISSUE THREAD

**Issue by deman4ik** [rid00z/FreshMvvm#20]
I try to install FreshMvvm NuGet Package to Universal Windows project (with Xamarin.Forms 1.5.1.6466-pre2) and have the following errors:
> FreshMvvm 0.0.6 is not compatible with UAP,Version=v10.0.
> Some packages are not compatible with UAP,Version=v10.0.

**Comment by deman4ik** [comment]
I forgot to write a solution - just update Xamarin.Forms Reference to 2.0 in FreshMvvm project.
Now Windows 10 Universal App work just fine with FreshMvvm.
Please update your NuGet Package referencing Xamarin.Forms 2.0

**Comment by EmilAlipiev** [comment]
you mean that you used the source instead of the nugetpackages and it worked for you?

**Comment by rid00z** [comment]
This should work correctly now, please let me know if it doesn't.
