### ISSUE TITLE
Fresh MVVM support for Radio Button group 

### ISSUE THREAD

**Issue by Elayaraj222** [rid00z/FreshMvvm#200]
Hi Micheal,

I have used Fresh MVVM for my project.

I have used Radio button with custom renderer approach and it works fine with the Normal approach (without Fresh MVVM). With Fresh MVVM, **selectedindex** is not working with radio button group. Kindly suggest me, how to implement the same with **Fresh Mvvm.**

I am using the Custom Radio Button and Radio Group with this below link.
https://github.com/kirtisagar/XamarinFormsRadioButtonXAML

**Comment by EmilAlipiev** [comment]
in your sample there is no freshmvvm implementation. If you post how you tried, I can give you better help. but according to my experience freshmvvm works for any custom tool for any binding. it has even nothing to do with freshmvvm. It just auto wireups your bindingcontext of the view. Does not much more than classic mvvm approach. just follow the convention in the documentation

**Comment by Elayaraj222** [comment]
Thanks for your support EmilAlipiev. I have done Radio Button and Radio Group with the help of XLAB samples. It works as I Expected.
[https://github.com/XLabs/Xamarin-Forms-Labs]
