### ISSUE TITLE
Samples doesn't build

### ISSUE THREAD

**Issue by fgiacomelli** [rid00z/FreshMvvm#202]
Hello, simply downloading the repository and building from scratch the sample project doesn't build.

Updating the packages solve the problem if I remove the obsolete [NotifyPropertyChanged] attribute from classes where is declared

**Comment by EmilAlipiev** [comment]
I think that you have a problem in your build. I recently was able to run the sample project. beside that freshmvvm is pretty straightforward. you dont even need to run samples.

**Comment by fgiacomelli** [comment]
I know, mine was only a test with the latest version of packages, but if you think that's not important that samples are updated and buildable with the latest version of dll and visual studio is not a problem. Thank you

**Comment by mekinney** [comment]
This fork - https://github.com/mekinney/FreshMvvm - has a solution file and samples that build.  It uses the latest version of freshmvvm from Nuget.
