### ISSUE TITLE
Does this work with Xamarin Forms 2?

### ISSUE THREAD

**Issue by robertbaker** [rid00z/FreshMvvm#21]

**Comment by rid00z** [comment]
Yes this should. Are you having any issues?

**Comment by robertbaker** [comment]
No...not yet anyway. I'm starting a Xamarin Forms 2 project, building android first. I'm thinking of using this for MVVM and a better DI system (maybe use TinyIOC).

Currently I'm just using Xamarin Forms doing unit tests and I have to reference the Xamarin.Forms in my Unit test project, which causes more issues.

Could you tell me some differences between this and mvvmcross?

**Comment by robertbaker** [comment]
@rid00z Looks like this is using an old version of xamarin forms.

**Comment by rid00z** [comment]
Generally, it should be forwards compatible.


*Michael Ridland | Technical Director | Xamarin MVP*

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com

**Comment by rid00z** [comment]
FreshMvvm is based on MvvmCross conventions but takes into account Xamarin.Forms has 90% of what's needed for Mvvm. FreshMvvm is only the extra 10% that's required, while MvvmCross and Xamarin.Forms have a huge amount of duplicated functionality.

**Comment by jfversluis** [comment]
I have been using FreshMvvm in a Forms 2 project and didn't run into any problems as of yet!
