### ISSUE TITLE
Where are the release notes? Whats new?

### ISSUE THREAD

**Issue by EmilAlipiev** [rid00z/FreshMvvm#211]
Hi,

There 2.2.4 version and i would like to know what are the changes for this release but i cant find it. Do you keep some release notes? i cant even see any releases under release tab.

thanks.

**Comment by VahidShir** [comment]
I just took a look at NuGet link and there exists the Release notes:

> 2.2.4
>    New method on FreshMasterDetailNavigationContainer, a none generic version of AddPage which adds ability for dynamically built menu's
>    FreshAwaitCommand now supports canExecute Function
