### ISSUE TITLE
Update TinyIOC

### ISSUE THREAD

**Issue by robertbaker** [rid00z/FreshMvvm#22]
I'm interested to know why TinyIOC is being included in the src but the namespace is just changed.

It would be better to just have TinyIOC as a nuget dependant.  The version of TinyIOC included is outdated.

**Comment by robertbaker** [comment]
I updated the dependencies to the project. https://github.com/robertbaker/FreshMvvm/tree/Forms2

The samples have some minor issues compiling. I'm not sure how different the FreshTinyIOC is from TinyIOC, so I left that alone for now.

My goal would be to reference the nuget package and just have your customizations in a cs file.

**Comment by rid00z** [comment]
The TinyIOC nuget doesn't work in Xamarin studio, that's why it's the way
it is.

On Wednesday, 25 November 2015, Robert Baker <notifications@github.com>
wrote:

> I'm interested to know why TinyIOC is being included in the src but the
> namespace is just changed.
>
> It would be better to just have TinyIOC as a nuget dependant. The version
> of TinyIOC included is outdated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rid00z/FreshMvvm/issues/22>.
>


-- 

*Michael Ridland | Technical Director | Xamarin MVP*

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com

**Comment by robertbaker** [comment]
@rid00z Is this implementation just the TinyIOC.cs and the ReverseTypeExtender.cs combined? Or is there customization besides just the namespace change/ method renaming?

**Comment by rid00z** [comment]
Traditionally TinyIOC has never worked in PCLs this is a customised version that does.

**Comment by BNoohi** [comment]
@rid00z I was under the impression TInyIoC does handled PCL now? Would it worthwhile to try? Otherwise this issue is a non-issue.

**Comment by robertbaker** [comment]
@BNoohi @rid00z Looks like it does.

**Comment by BNoohi** [comment]
Ok, unless @rid00z you're strongly opposed, you (or whomever) can get a pull request with the proposed changes?

If this works well, it would ensure TinyIoC/FreshIoC would be inline with the community.

**Comment by rid00z** [comment]
I've done some changes recently and should be able to use the TinyIOC PCL and also allow for other IOC containers. I will push them up soon.

**Comment by robertbaker** [comment]
@rid00z I would like to switch to DryIOC as it's the fastest and full featured IOC container for .net. Hoping the changes will allow me to use it!

**Comment by BNoohi** [comment]
@rid00z  That's great news!

**Comment by rid00z** [comment]
This has been solved in current codebase and will be included in next release.
