### ISSUE TITLE
.NETStandard 2.0?

### ISSUE THREAD

**Issue by rachael-ross** [rid00z/FreshMvvm#229]
Can you tell me if .NETStandard 2.0 is now supported?

**Comment by jonkas2211** [comment]
Hallo @rachael-ross,

i did it myself. You can check it out at my forked verison of this https://github.com/jonkas2211/FreshMvvm
If you want to create a nuget, then you need to adjust the nuspec, because if forgot about it.

**Comment by libin85** [comment]
@rachael-ross : We are currently working on the latest version of .NetStandard and will be coming out soon. @jonkas2211 , thanks for taking the effort to do the interim support. Appreciate your support for the framework.
