### ISSUE TITLE
Arc.Userdialogs

### ISSUE THREAD

**Issue by MBrekhof** [rid00z/FreshMvvm#23]
I'm using Arc.Userdialogs together with FreshMvvm which works well with one exception: the messages(toasts) appear and reappear as if there is an additional refresh/repaint by FreshMvvm.

Did you ever use Arc.Userdialogs with FreshMvvm and are there any gotchas or whatever?

**Comment by rid00z** [comment]
It's always worked well for me. Sounds like a user dialogs issue?

On Wednesday, 25 November 2015, MBrekhof <notifications@github.com> wrote:

> I'm using Arc.Userdialogs together with FreshMvvm which works well with
> one exception: the messages(toasts) appear and reappear as if there is an
> additional refresh/repaint by FreshMvvm.
>
> Did you ever use Arc.Userdialogs with FreshMvvm and are there any gotchas
> or whatever?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rid00z/FreshMvvm/issues/23>.
>


-- 

*Michael Ridland | Technical Director | Xamarin MVP*

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com

**Comment by MBrekhof** [comment]
I'll ask them also, just in case:

This works as expected:

    [ImplementPropertyChanged]
    public class GebruikerPageModel : FreshBasePageModel
    {
        IDatabaseService _databaseService;
        private IUserDialogs _userDialogs;
        public Gebruiker gebruiker { get; set; }

        public GebruikerPageModel(IDatabaseService databaseService,IUserDialogs userDialogs)
        {
            _databaseService = databaseService;
            _userDialogs = userDialogs;
        }

        public override void Init(object initData)
        {
....
        }

        public Command SaveGebruiker
        {
            get       {
                return new Command(() =>
                {
                    if (!CrossConnectivity.Current.IsConnected)
                    {
                        _userDialogs.ErrorToast("Probleem", "Geen werkende Wifi verbinding", 5000);
                    }
                    else
                    {
                        List<Inbox> testboxes = _databaseService.GetInboxes();
                        if (testboxes?.Count == 0)
                            _userDialogs.ErrorToast("Probleem", "Geen inboxen gevonden, gegevens correct?", 5000);
                        else
                        {
                            _databaseService.SaveGebruiker(gebruiker);
                            App.CurrentUser = gebruiker;
                        }
                    }
                    CoreMethods.PopPageModel(gebruiker);
                });
            }
        }
   }

This produces some red flashes:
   [ImplementPropertyChanged]
    public class InboxListPageModel : FreshBasePageModel
    {
        IDatabaseService  _databaseService;
        IUserDialogs _userDialogs;

        private string inboxesHeader = "Inboxen";

        public string InboxesHeader
        {
            get { return inboxesHeader; }
            set { inboxesHeader = value; }
        }

        public InboxListPageModel(IDatabaseService databaseService, IUserDialogs userDialogs)
        {
            _databaseService = databaseService;
            _userDialogs = userDialogs;
        }

        public ObservableCollection<Inbox> Inboxes { get; set; }

        public override void Init(object initData)
        {

            Gebruiker gebr = App.CurrentUser;
            if (App.CurrentUser == null)
            {
                _userDialogs.ShowError("Geen Digidoc ID ingevuld.", 3000);
            }
            else
            {
                if (String.IsNullOrEmpty(App.CurrentUser.Naam))
                    _userDialogs.ShowError("Geen correcte Digidoc ID ingevuld.", 3000);
            }
            if (!CrossConnectivity.Current.IsConnected)
            {
                _userDialogs.ErrorToast("Probleem","Er is geen Wifi beschikbaar", 3000);
            }
        }
....

**Comment by rid00z** [comment]
You should really be loading a dialog during the init method. Normally I
never have to do that, dialogs are shown in commands.

On Thursday, 26 November 2015, MBrekhof <notifications@github.com> wrote:

> I'll ask them also, just in case:
>
> This works as expected:
>
> [ImplementPropertyChanged]
> public class GebruikerPageModel : FreshBasePageModel
> {
>     IDatabaseService _databaseService;
>     private IUserDialogs _userDialogs;
>     public Gebruiker gebruiker { get; set; }
>
>     public GebruikerPageModel(IDatabaseService databaseService,IUserDialogs userDialogs)
>     {
>         _databaseService = databaseService;
>         _userDialogs = userDialogs;
>     }
>
>     public override void Init(object initData)
>     {
>
> ....
> }
>
>     public Command SaveGebruiker
>     {
>         get       {
>             return new Command(() =>
>             {
>                 if (!CrossConnectivity.Current.IsConnected)
>                 {
>                     _userDialogs.ErrorToast("Probleem", "Geen werkende Wifi verbinding", 5000);
>                 }
>                 else
>                 {
>                     List<Inbox> testboxes = _databaseService.GetInboxes();
>                     if (testboxes?.Count == 0)
>                         _userDialogs.ErrorToast("Probleem", "Geen inboxen gevonden, gegevens correct?", 5000);
>                     else
>                     {
>                         _databaseService.SaveGebruiker(gebruiker);
>                         App.CurrentUser = gebruiker;
>                     }
>                 }
>                 CoreMethods.PopPageModel(gebruiker);
>             });
>         }
>     }
>
> }
>
> This produces some red flashes:
> [ImplementPropertyChanged]
> public class InboxListPageModel : FreshBasePageModel
> {
> IDatabaseService _databaseService;
> IUserDialogs _userDialogs;
>
>     private string inboxesHeader = "Inboxen";
>
>     public string InboxesHeader
>     {
>         get { return inboxesHeader; }
>         set { inboxesHeader = value; }
>     }
>
>     public InboxListPageModel(IDatabaseService databaseService, IUserDialogs userDialogs)
>     {
>         _databaseService = databaseService;
>         _userDialogs = userDialogs;
>     }
>
>     public ObservableCollection<Inbox> Inboxes { get; set; }
>
>     public override void Init(object initData)
>     {
>
>         Gebruiker gebr = App.CurrentUser;
>         if (App.CurrentUser == null)
>         {
>             _userDialogs.ShowError("Geen Digidoc ID ingevuld.", 3000);
>         }
>         else
>         {
>             if (String.IsNullOrEmpty(App.CurrentUser.Naam))
>                 _userDialogs.ShowError("Geen correcte Digidoc ID ingevuld.", 3000);
>         }
>         if (!CrossConnectivity.Current.IsConnected)
>         {
>             _userDialogs.ErrorToast("Probleem","Er is geen Wifi beschikbaar", 3000);
>         }
>     }
>
> ....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rid00z/FreshMvvm/issues/23#issuecomment-159703864>.
>


-- 

*Michael Ridland | Technical Director | Xamarin MVP*

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com

**Comment by rid00z** [comment]
Shouldn't

On Thursday, 26 November 2015, Michael Ridland <rid00z@gmail.com> wrote:

>
> You should really be loading a dialog during the init method. Normally I
> never have to do that, dialogs are shown in commands.
>
> On Thursday, 26 November 2015, MBrekhof <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> I'll ask them also, just in case:
>>
>> This works as expected:
>>
>> [ImplementPropertyChanged]
>> public class GebruikerPageModel : FreshBasePageModel
>> {
>>     IDatabaseService _databaseService;
>>     private IUserDialogs _userDialogs;
>>     public Gebruiker gebruiker { get; set; }
>>
>>     public GebruikerPageModel(IDatabaseService databaseService,IUserDialogs userDialogs)
>>     {
>>         _databaseService = databaseService;
>>         _userDialogs = userDialogs;
>>     }
>>
>>     public override void Init(object initData)
>>     {
>>
>> ....
>> }
>>
>>     public Command SaveGebruiker
>>     {
>>         get       {
>>             return new Command(() =>
>>             {
>>                 if (!CrossConnectivity.Current.IsConnected)
>>                 {
>>                     _userDialogs.ErrorToast("Probleem", "Geen werkende Wifi verbinding", 5000);
>>                 }
>>                 else
>>                 {
>>                     List<Inbox> testboxes = _databaseService.GetInboxes();
>>                     if (testboxes?.Count == 0)
>>                         _userDialogs.ErrorToast("Probleem", "Geen inboxen gevonden, gegevens correct?", 5000);
>>                     else
>>                     {
>>                         _databaseService.SaveGebruiker(gebruiker);
>>                         App.CurrentUser = gebruiker;
>>                     }
>>                 }
>>                 CoreMethods.PopPageModel(gebruiker);
>>             });
>>         }
>>     }
>>
>> }
>>
>> This produces some red flashes:
>> [ImplementPropertyChanged]
>> public class InboxListPageModel : FreshBasePageModel
>> {
>> IDatabaseService _databaseService;
>> IUserDialogs _userDialogs;
>>
>>     private string inboxesHeader = "Inboxen";
>>
>>     public string InboxesHeader
>>     {
>>         get { return inboxesHeader; }
>>         set { inboxesHeader = value; }
>>     }
>>
>>     public InboxListPageModel(IDatabaseService databaseService, IUserDialogs userDialogs)
>>     {
>>         _databaseService = databaseService;
>>         _userDialogs = userDialogs;
>>     }
>>
>>     public ObservableCollection<Inbox> Inboxes { get; set; }
>>
>>     public override void Init(object initData)
>>     {
>>
>>         Gebruiker gebr = App.CurrentUser;
>>         if (App.CurrentUser == null)
>>         {
>>             _userDialogs.ShowError("Geen Digidoc ID ingevuld.", 3000);
>>         }
>>         else
>>         {
>>             if (String.IsNullOrEmpty(App.CurrentUser.Naam))
>>                 _userDialogs.ShowError("Geen correcte Digidoc ID ingevuld.", 3000);
>>         }
>>         if (!CrossConnectivity.Current.IsConnected)
>>         {
>>             _userDialogs.ErrorToast("Probleem","Er is geen Wifi beschikbaar", 3000);
>>         }
>>     }
>>
>> ....
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rid00z/FreshMvvm/issues/23#issuecomment-159703864>.
>>
>
>
> --
>
> *Michael Ridland | Technical Director | Xamarin MVP*
>
> XAM Consulting - Mobile Technology Specialists
>
> www.xam-consulting.com
>
> Blog: www.michaelridland.com
>
>
>
>

-- 

*Michael Ridland | Technical Director | Xamarin MVP*

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com
