### ISSUE TITLE
AddINotifyPropertyChangedInterface vs ImplementPropertyChanged in Fody with FreshMVVM Base

### ISSUE THREAD

**Issue by tallmanBS** [rid00z/FreshMvvm#233]
Hello,
I had 

> [ImplementPropertyChanged]

    class LocListPageModel : FreshMvvm.FreshBasePageModel
    {
        public bool tbAddVisible { get; set; }

when I changed value of tbAddVisible, the propertychanged was triggered, but now after changing
to

> [PropertyChanged.AddINotifyPropertyChangedInterface]

    class LocListPageModel : FreshMvvm.FreshBasePageModel
    {
        public bool tbAddVisible { get; set; }

it's not.  I can issue the RaisePropertyChanged(nameof(tbAddVisible)) and it will trigger, but it used to be automatic and I need it to be (for the entire app since worked that way).  Is this a bug or am I doing it wrong?
I'm using current versions of Freshmvvm (2.2.4) and PropertyChanged.Fody (2.5.8)
Thanks.
Brent

**Comment by tallmanBS** [comment]
I think I found the problem.  So for the next person.  My Portable/Forms project for some reason was missing this line.
<Import Project="..\..\packages\Fody.3.1.3\build\Fody.targets" Condition="Exists('..\..\packages\Fody.3.1.3\build\Fody.targets')" />

After hours of comparing your sample proiect with my existing, found this was missing and when I added, then the auto notifys started working.  I don't know why it went away when I upgraded the Fody through nuget, but it did.
Hope this helps someone else.
Brent

**Comment by avorobjovs** [comment]
> I think I found the problem. So for the next person. My Portable/Forms project for some reason was missing this line.
> After hours of comparing your sample proiect with my existing, found this was missing and when I added, then the auto notifys started working. I don't know why it went away when I upgraded the Fody through nuget, but it did.
> Hope this helps someone else.
> Brent

Hi Brent,
Could you tell me please, what line was missed in your project? It looks like I have a similar issue now.
- Aleksandrs

**Comment by mos379** [comment]
> I think I found the problem. So for the next person. My Portable/Forms project for some reason was missing this line.
@tallmanBS what was that line?

**Comment by tallmanBS** [comment]
My apologies as I can't believe I didn't include the line.   I've gone back and looked at repository, but it been too long and the history isn't there that far back.  And I don't remember.  Sorry.
