### ISSUE TITLE
How freshmvvm navigation works with bottom navigation bar 

### ISSUE THREAD

**Issue by swapnil591** [rid00z/FreshMvvm#234]

**Comment by GarethWinterSteris** [comment]
Not sure you will be able to until Fresh is updated to use the latest version of Xamarin Forms.

**Comment by gazwinter** [comment]
Not sure you will be able to until Fresh is updated to use the latest version of Xamarin Forms

**Comment by gazwinter** [comment]
You could try the stuff listed here though and it may work:

[https://developer.xamarin.com/releases/xamarin-forms/xamarin-forms-3.1/3.1.0-sr2/](url)

**Comment by swapnil591** [comment]
Thanks

**Comment by twenzel** [comment]
It works for me.

In `App.xaml.cs`:
```
var tabbedNavigation = new FreshTabbedNavigationContainer();
tabbedNavigation.On<Xamarin.Forms.PlatformConfiguration.Android>().SetToolbarPlacement(ToolbarPlacement.Bottom);
tabbedNavigation.AddTab<xyPageModel>("xy", "xy.png");
tabbedNavigation.AddTab<yyyyPageModel>("yyy", "yyyy.png");
tabbedNavigation.AddTab<cccPageModel>("ccc", "cccc.png");            

MainPage = loginStack;
```

**Comment by libin85** [comment]
solution suggested by @twenzel  should work.
