### ISSUE TITLE
Hide The empty rows in side menu

### ISSUE THREAD

**Issue by Shivaprabhu049** [rid00z/FreshMvvm#236]
Hi,
   How to hide the empty rows in FreshMasterDetailNavigationContainer  side Menu.

**Comment by EmilAlipiev** [comment]
what do you mean? can you give some example?

**Comment by libin85** [comment]
Assume that you are talking about the iOS. This has nothing to do with the FreshMvvm or Xamarin, but thats the default behavour of iOS ListViews. You can remove the extra lines, by adding the Property `Footer=""` into the ListView element. If you still have issues with the framework, please feel free to open another issue with more detailed explanations and some code samples
