### ISSUE TITLE
Can I show Toast using Fresh mvvm?

### ISSUE THREAD

**Issue by arvindrajachourasiya** [rid00z/FreshMvvm#240]
We can show alert using   `CoreMethods.DisplayAlert`  in FreshMvvm. how  can I show `Toast` message?
Thank you

**Comment by EmilAlipiev** [comment]
it is not implemented. you cannot show. please use Acr userdialogs or other library for toast messages

**Comment by Charuwaka** [comment]
Yes use ACR Dailogs

**Comment by libin85** [comment]
Yes you could use ACR User Dailogs plugin with FreshMvvm to show the toast messages. The plugin is not included with the framework. Please check here for more details https://github.com/aritchie/userdialogs
