### ISSUE TITLE
FreshMVVM - The future

### ISSUE THREAD

**Issue by Surfrat** [rid00z/FreshMvvm#243]
I am concerned that this project has ground to a halt. Is it a viable choice to partner Xamarin Forms.

Rid00z, what are your plans for this project?

**Comment by Surfrat** [comment]
Looks like I have my answer....

**Comment by libin85** [comment]
@Surfrat : We have planned for a new release soon with lot of exciting goodies. The motto of FreshMvvm is to be the number one MVVM framework to build Xamarin forms mobile applications as always. We are working towards some really cool stuffs and Michael is hands on to it now. We appreciate your feedback and welcome any contributions that can make the framework even better.

**Comment by Surfrat** [comment]
Excellent news. Thank you FreshMVVM team.

**Comment by LeoJHarris** [comment]
@libin85 any rough eta when these can be expected? The Nuget package seems really old and there's a couple of PR hanging around. Are some of these PR going to be merged and included in the next latest nuget version? I've already migrated some of our projects to use FreshMVVM and so far really enjoying it! So great work to @rid00z, yourself and any other contributors on this repo 👍 🥇

**Comment by LeoJHarris** [comment]
https://www.nuget.org/packages/FreshMvvm/3.0.0
