### ISSUE TITLE
Handling Navigation correctly in OnResume Event

### ISSUE THREAD

**Issue by stevenengland** [rid00z/FreshMvvm#249]
Hi there, I am wondering what is a working (and even better a good) practice to resume to the specific last work item that was open in the app before the app got suspended. An example:
Lets say I have a MasterDetailNavigation containing a MainPageModel that displays an overview of all current ToDos.

The App is initialized as follows:
```
public App() // App.xaml.cs
{
	this.InitializeComponent();
	var masterDetailNav = new FreshMasterDetailNavigationContainer(NavigationContainerNames.MainContainer);
	masterDetailNav.Init(LanguageResources.MenuPageTitle, "ic_menu_grey_600_36dp.png");
	masterDetailNav.AddPage<MainPageModel>(LanguageResources.MainPageTitle, "Topics", "ic_home_grey_600_36dp.png", null);
	masterDetailNav.AddPage<SettingsPageModel>(LanguageResources.SettingsPageTitle, "Settings", "ic_settings_grey_600_36dp.png", null);
	...

	// Loading the standard container
	this.MainPage = masterDetailNav;
}
```

In the MainPageModel there is the functionality that loads a chosen or a newly created ToDo with a seperate navigation

```
private async Task OpenToDo(object listItem) // MainPageModel.cs
{
	...
	var todo = listItem as ToDo;
	await this.CoreMethods.PushPageModelWithNewNavigation<ToDoEditPageModel>(todo);
	...
}
```

In case a user does not finish the ToDo workflow I want the app to resume the last opened ToDo

```
protected override void OnResume() // App.xaml.cs
{
	// Determine the last open ToDo from Settings or Db
	var todo = GetItemFromSomewhere(); 
	// Resolve the PageModel from where I would normally call the new naviation to ToDoEditPageModel
	var page = FreshPageModelResolver.ResolvePageModel<MainPageModel>();
	var pageModel = page.GetModel();
	pageModel.CoreMethods.PopToRoot(false); // I didn't find out yet which navigation state is resumed at all (MasterDetail stack or the one from PushPageModelWithNewNavigation)
	// Imitate the MainPageModel behaviour
	pageModel.CoreMethods.PushPageModelWithNewNavigation<ToDoEditPageModel>(todo);
}
```
Is this an approach that you would recommend?
I could not find any hint regarding the FreshMvvm scenario. The approach I'm trying to copy comes from here: [Xamarin Sqlite Example](https://github.com/xamarin/xamarin-forms-samples/blob/f56943da83b56f21086f8bd4124436dfc4434f34/Todo/Todo/App.cs)
```
if (ResumeAtTodoId >= 0)
{
	var todoPage = new TodoItemPage();
	todoPage.BindingContext = await Database.GetItemAsync(ResumeAtTodoId);
	await MainPage.Navigation.PushAsync(todoPage, false); // no animation
}
```

**Comment by libin85** [comment]
Hi Steven,
If I understand your question correctly, neither Xamarin Forms or FreshMvvm provides any direct support to do what you are after. But you could write your own logic and it should work like a charm. We have recently done something similar in our recent project. What you might need to do is, in the ViewIsDisappearing method to serialise the page data and save it to a store( can be sqlite or any other form). Use reflection if u need to serialise different pages dynamically.

One of the app load, check if there is a a record existing and then navigate to that page, Again using reflection and generics.

I hope that helps.
