### ISSUE TITLE
Cannot find PageModel

### ISSUE THREAD

**Issue by robertbaker** [rid00z/FreshMvvm#25]
I been following your sample, using Xamarin Forms 2. It's not finding my LoginPageModel which is derived from FreshBasePageModel. I scrubbed through the sample app to see if I'm missing anything and I have what's needed.

**Comment by therealjohn** [comment]
@robertbaker Do you have any more context on this error? What do you mean by `PageModel`. 

For a `Page`, no base class is necessary for anything in this framework to function. Only your "viewmodels" need the `FreshBasePageModel` base.

**Comment by robertbaker** [comment]
I don't. I have switched to mvvmcross, I'm doing native views now. By
pagemodel I meant my view model.
