### ISSUE TITLE
TabPage Badge

### ISSUE THREAD

**Issue by marcoseraphin** [rid00z/FreshMvvm#253]
Hi,

I want to display a TabPage badge for indicating new messages using FreshMVVM.

I have found this Plugin.Badge NuGet package: https://github.com/xabre/xamarin-forms-tab-badge which works for Xamarin.Forms.

BUT I think the custom renderer uses the original TabbedPage class and it did not work with the FreshTabbedNavigationContainer from FreshMVVM because it is inherited.

Any idea how to show a TabbedPage badge in combination with FreshMVVM ?

Thanx

Marco

**Comment by libin85** [comment]
Hi @marcoseraphin ,

It should work without any issues with FreshMvvm. I have tested it and it works with no issues.

**Comment by marcoseraphin** [comment]
Hi @libin85 ,

thank you very much....the sample works and now my current project also shows the badge.
The only difference.

I did it in the C# code in the App.xaml.cs (perhaps to early) and your did it in the page xaml.

TabBadge.SetBadgeText(messagePage, "3");

I changed your sample to bind the badge text and it works...so you made my day...

Best

Marco

**Comment by libin85** [comment]
Happy that you got it sorted :)
