### ISSUE TITLE
View Reference or click event into Pagemodel?

### ISSUE THREAD

**Issue by LeoJHarris** [rid00z/FreshMvvm#257]
Hi there, I need to get a some data from a view component, I could get a reference to it or just create a click handler and will it would both create reference in the xaml.cs code behind. 

Although since I want to keep my business logic in the pagemodel and keep the xaml.cs file fairly empty. How could I get a reference from a view into my page model class?

Say I have a picker and I wanted to set the selected item manually or something? How could I do this all from the pagemodel?

Hope it makes sense what asking.

**Comment by LeoJHarris** [comment]
I guess Im partly asking how to share views, or data between the page and pagemodel.

**Comment by libin85** [comment]
Use Bindable Properties in your control, and you will be able to get data in you view into pagemodel. But to be honest, this has got nothing to do with FreshMvvm its more to do with Xamarin Forms

**Comment by LeoJHarris** [comment]
Sorry had quickly figured it out upon asking. Thanks!
