### ISSUE TITLE
MVVM with Rg.Plugins.Popup

### ISSUE THREAD

**Issue by LeoJHarris** [rid00z/FreshMvvm#258]
Hi there, I am trying to migrate a project over to use FreshMVVM, i have been using the Rg.Plugins.Popup library, 

I had found a solution to possibly able to use the FreshMVVM with the popup plugin:

```csharp
public virtual Task PushPage(Xamarin.Forms.Page page, FreshBasePageModel model, bool modal = false, bool animate = true)
{
if (modal)
{
if (page is PopupPage)
{
return Navigation.PushPopupAsync(page as PopupPage, animate);
}
...
}
...
        return Navigation.PushAsync(page, animate);
    }
```

Has any one tried around to make these two plugins work together, or how I could alter the above to make work and how the integration might work... Sorry am new to FreshMVVM and like it much but just weighing up if this is the right fit for our future projects. I wasnt

**Comment by libin85** [comment]
@LeoJHarris : Hey Leo. Are you asking how you could push a  Rg.Plugins.Popup from a PageModel?

**Comment by LeoJHarris** [comment]
Hi @libin85 thats correct.

Am trying below and as per wiki creating a custom Navigation extending `Xamarin.Forms.NavigationPage, IFreshNavigationService`

copied the source code on the FreshNavigationContainer and overriding:

`public virtual Task PushPage(Xamarin.Forms.Page page, FreshBasePageModel model, bool modal = false, bool animate = true)
        {
            if (modal)
            {
                if (page is PopupPage)
                {
                    return Navigation.PushPopupAsync(page as PopupPage, animate);
                }
                else
                {
                    return Navigation.PushModalAsync(CreateContainerPageSafe(page), animate);
                }
            }
            return Navigation.PushAsync(page, animate);
        }` 

Haven't tested yet , but suspect will work fine.

**Comment by LeoJHarris** [comment]
The above works fine, whether the best solution im not sure but it does work.

**Comment by libin85** [comment]
@LeoJHarris : I have created a extension library that does the trick. Have a look and let me know of any suggestions. https://github.com/libin85/FreshMvvm.Popup . I will soon make it as a nuget

**Comment by LeoJHarris** [comment]
Great I will try it and let you know . Thanks

**Comment by LeoJHarris** [comment]
Your extension works nicely, look forward to the nuget, I think other people having been looking for this:

https://github.com/rotorgames/Rg.Plugins.Popup/issues/27

**Comment by libin85** [comment]
Yup. I have stumbled upon it when i was looking for a solution too :)
