### ISSUE TITLE
Navigation Issue - popping back to first page

### ISSUE THREAD

**Issue by LeoJHarris** [rid00z/FreshMvvm#259]
Hi there, I am having a slight navigation issue in that I am trying to pop back to the root page with navigation like this A => B => C (PopupPage) then pop back to A, currently am getting an exception thrown: FreshTinyIoC.TinyIoCResolutionException: Resolve failed: IFreshNavigationService

Initially in the App.cs file I have:

```csharp
Page loginPage = FreshPageModelResolver.ResolvePageModel<LoginPageModel>();
Page roomsListPageModel = FreshPageModelResolver.ResolvePageModel<RoomListPageModel>();

CustomNavigationService loginContainer = new CustomNavigationService(loginPage, NavigationStacks.LoginNavigationStack);
CustomNavigationService roomsListViewContainer = new CustomNavigationService(roomsListPageModel, NavigationStacks.MainAppStack);

MainPage = loginContainer;
```

When I login a user from the LoginPageModel I do this:

```csharp
CoreMethods.SwitchOutRootNavigation(NavigationStacks.MainAppStack);
```

So then from on the RoomListPageModel I push another page on the stack like this:

```csharp
await CoreMethods.PushPageModel<RoomPageModel>(true);
```

then on the RooPageModel I push a Popup page on (using the extension method you had provided, thank you for that):

```csharp
await CoreMethods.PushPopupPageModel<CancelTaskReasonPageModel>(new ReasonCancelled
                        {
                            CleanTime = new TimeSpan(_hours, _mins, _secs),
                            responseGetRoomHousekeepingTasks = ResponseGetRoomHousekeeping,
                            tasksRemaining = tasksRemaining
                        }, true);
```

Now the issue is getting back the RoomListPage which should be the root page:

```csharp
await CoreMethods.PopPopupPageModel(false);
await CoreMethods.PopToRoot(false);
```

also tried:

```csharp
await App.Current.MainPage.Navigation.PopPopupAsync();
await CoreMethods.PopPageModel(false);
```

Initially I was able to do this before trying FreshMVVM and it worked fine:

```csharp
await App.Current.MainPage.Navigation.PopPopupAsync();
await App.Current.MainPage.Navigation.PopToRootAsync();
```

**Comment by libin85** [comment]
I again believe this is not an issue with the FeshMvvm. And what I guess is that we have two different navigation stacks. But what you could do is pass an instance of FreshBaseViewModel to the popup and from that instance if u do PopToRoot(), i am pretty sure it will work.

    public class PopupNavigationModel
    {
        public FreshBasePageModel ContentPageModel { get; set; }
        public object PageData { get; set; }
    }

Send an instance to the above model. And Use ContentPageModel.CoreMethods.PopToRootAsync().

I hope that works

**Comment by LeoJHarris** [comment]
@libin85 sorry my bad I actually had in one of the push methods modal set to true hence it wasn't removing that page.

Although to remove the Popup and page I just call:

```csharp
await ReasonCancelled.ContentPageModel.CoreMethods.PopPopupPageModel(true);
await ReasonCancelled.ContentPageModel.CoreMethods.PopToRoot(true);
```

Thanks

**Comment by libin85** [comment]
@LeoJHarris : Please update the Rg.Plugin.Popups to the latest version(1.1.5.188) and you don't need any of the work arounds that I suggested. Check my sample, I have updated with these changes.
