### ISSUE TITLE
Sample App is broken and doesnt build due to Nuget version not existing publicly

### ISSUE THREAD

**Issue by arggrande** [rid00z/FreshMvvm#262]
Hi,

It looks like there was a PR merge (#252) recently that upped the current version of the library and sample app to XF 3.x and .NET Standard 2 (yay!), however on pulling the repo down in its current state, the version of FreshMvvm being referenced in the `FreshMvvmApp.csproj` doesnt exist on the public nuget feed.

`<PackageReference Include="FreshMvvm" Version="3.0.0" />`

Is there an ETA on when this will be released?

See #261 for a related question on this.

**Comment by libin85** [comment]
@arggrande : Hi Adam, can you confirm if things are working okay for you now?

**Comment by libin85** [comment]
Closing this issue, I have tested and its working okay since we have the version 3.0 available in nuget. If you have any issues feel free to reopen
