### ISSUE TITLE
iOS: Cannot set CurrentPage of TabbedPage: only a view controller in the tab bar controller's list of view controllers can be selected.

### ISSUE THREAD

**Issue by LeoJHarris** [rid00z/FreshMvvm#264]
Hi there, am trying to set the current page for tabbedPage in code but not having too much luck:

```csharp
(BindingContext as LoginPageModel)?.CoreMethods.SwitchOutRootNavigation(NavigationStacks.MainAppStack);
                                if (Settings.CurrentUser.GetInHouseBooking() == default(CurrentBooking))
                                {
                                    if (Application.Current.MainPage is FreshTabbedNavigationContainer freshTabbedNavigation)
                                    {
                                        Page contentPage = (Page)freshTabbedNavigation.TabbedPages.ElementAt(2);
                                        freshTabbedNavigation.SelectedItem = contentPage;
                                        freshTabbedNavigation.CurrentPage = contentPage;
                                    }
                                }
```

I can confirm that correct page I want is in fact contentPage when I debug but the page is showing when the tabbedpage loads. I want child page of tabbed page at index 2 but I am getting the tab at index 0 showing which would be the default but am trying to override that.

The tabbedpage has not yet displayed at this point.

**Comment by LeoJHarris** [comment]
Edited code to:

```csharp
(BindingContext as LoginPageModel)?.CoreMethods.SwitchOutRootNavigation(NavigationStacks.MainAppStack);
                                if (Settings.CurrentUser.GetInHouseBooking() == default(CurrentBooking))
                                {
                                    if (Application.Current.MainPage is FreshTabbedNavigationContainer freshTabbedNavigation)
                                    {
                                        Page contentPage = (Page)freshTabbedNavigation.TabbedPages.ElementAt(2);
                                        freshTabbedNavigation.CurrentPage = contentPage;
                                    }
                                }
```

Throwing on iOS:

Foundation.MonoTouchException: Objective-C exception thrown.  Name: NSInvalidArgumentException Reason: -[UITabBarController setSelectedViewController:] only a view controller in the tab bar controller's list of view controllers can be selected.

Is there some way to resolve this, I thought we could programmatically set the CurrentPage of a tabbed page by the above.

**Comment by libin85** [comment]
Sorry @LeoJHarris , could you try to get a sample repo. Did'nt really get you

**Comment by LeoJHarris** [comment]
@libin85 sorry for the confusion, I have a TabbedPage with 4 children and basically given a condition I might want either the third child of the tabbedpage to be the current page or the first (before the tabbedpage is displayed. So directly after calling SwitchOutRootNavigation() that swaps to the tabbedpage I try assign the CurrentPage of the tabbed page that I want displayed first, however this doesn't seem to work but always displays the first child of the tabbed page as the CurrentPage but not the page I wanted (in this case the 3rd page i.e. booking page).

ill aim to attach a repo.

But below you can see at the point I assign to the CurrentPage/SelectedItem of the tabbedpage

![Capture](https://user-images.githubusercontent.com/5468757/57993676-20b4f700-7b0e-11e9-910e-1ff02f00bff6.PNG)

Then when tabbedpage displayed however the Bookings Page is not the selected/current page, but the first child is.

![device-2019-05-20-144642](https://user-images.githubusercontent.com/5468757/57993752-6e316400-7b0e-11e9-8c06-cbf93826f2dd.png)

**Comment by LeoJHarris** [comment]
Im just trying to programmatically set the 'My Booking' page as the selected page when the tabbedpage displays but by default it will set the first page which in my case is the my stay page.

**Comment by LeoJHarris** [comment]
[sample_TabbedPage.zip](https://github.com/rid00z/FreshMvvm/files/3199958/sample_TabbedPage.zip)

Hi @libin85 have attached repo, you see 3 Pages, Page2 and page3 are are children of the tabbed page in that order, Im trying to set Page3 as the CurrentPage when the tabbedpage shows but page2 keeps being shown as the currentpage.

**Comment by libin85** [comment]
@LeoJHarris : Sorry, been a bit crazy busy. Will look into over the weekend.

**Comment by LeoJHarris** [comment]
@libin85 okay appreciate that!

**Comment by LeoJHarris** [comment]
@libin85 : were you able to replicate the issue from the sample repo?

**Comment by libin85** [comment]
@LeoJHarris : SOrry mate been a bit busy at work these days. I saw the issue, I will update the project and upload it in here when I am back home.

**Comment by LeoJHarris** [comment]
@libin85 okay no worries, one thing i should note is that setting CurrentPage from a page already as a child in the tabbedpage seemed to work fine.

**Comment by libin85** [comment]
[sample_TabbedPage.zip](https://github.com/rid00z/FreshMvvm/files/3231775/sample_TabbedPage.zip)

Please check the sample, that should do the trick for you. Hope that helps.

**Comment by LeoJHarris** [comment]
Working on android nicely, will check on iOS but i suspect it will be fine.

**Comment by libin85** [comment]
Closing this issue @LeoJHarris , but feel free to reopen if u have any issues.
