### ISSUE TITLE
TabbedPage Android Lazyloading.

### ISSUE THREAD

**Issue by thiagoparabas** [rid00z/FreshMvvm#266]
Need to be created in FreshMVVM a way to have a Lazy Loading in TabbedPage, in android it runs all in the build.

**Comment by thiagoparabas** [comment]
Nothing? @rid00z 

Is possible?

**Comment by libin85** [comment]
@thiagoparabas : Thats just the default behavior of how Android tabs work. Not just specific to FreshMvvm or Xamarin. But if you want to lazy load the tabs, you can do something like this. https://enginecore.blogspot.com/2019/01/xamarin-forms-lazy-load-tabs-in_10.html .
