### ISSUE TITLE
How to handle delay between page popping and pushing?

### ISSUE THREAD

**Issue by spogulis** [rid00z/FreshMvvm#268]
Two things that have been frustrating me for many days now.
1) I have an ObservableCollection<model> in one page which is tied to a Listview from which, in turn, an ItemTapped event through a behavior invokes Command in my page. This command pushes a new page where I can edit properties of the object. There I have a command to pop the new page and here comes the problem: no matter what I do, the first page's ListView doesn't update even though the ObservableCollection has the relevant data. Even the selected item stays selected. Tried binding to SelectedItem of the ListView but that doesn't help.

2) Considering this issue, I've chosen to do the following: 
a) Pop page1 when pushing page2; 
b) Pop page2 and push page1 anew. It's not the best solution but at least it does the trick.

But there is at least a second long delay after popping and before the new page is displayed. In this second or so the previous page in the stack (main app page in my case) is displayed for a brief moment. Is there any way to add some kind of a mask for this transition?

**Comment by libin85** [comment]
@spogulis : has the model itself implemented the INotifyPropertyChanged?  I understand you are using  an observable collection, but that will only propagate the changes if an item is added or deleted to the collection. Not when a property within the model is changed. Hope that helps

**Comment by spogulis** [comment]
I ended up not popping the page1 when navigating to page2. Instead, after popping page2, I call PreviousPageModel.ReverseInit() and clear/reload data from db. This is not the best solution though.

All my page models are inheriting from a base class which has INotifyPropertyChanged implemented. Despite that, shouldn't ObservableCollection notify of changes automatically (without the interface)?

Any way to force it to propagate changes without changing the length of the collection?

**Comment by libin85** [comment]
Did u call `RaisePropertyChanged("Propertyname")`

**Comment by spogulis** [comment]
Yes, of course.

**Comment by rid00z** [comment]
@spogulis I'm just going to close this off because, as discussed this is not to do with FreshMvvm.. it's more Xamarin.Forms and c#.
