### ISSUE TITLE
IoC Generic type not working

### ISSUE THREAD

**Issue by winnertech** [rid00z/FreshMvvm#270]
I have tow types:

IRepository<T>
Repository<T>

In FreshMVVM IoC not exist option for type:

container.Register(typeof(IRepository<>), typeof(AzureRepository<>));

Please exist possible implementation?

**Comment by rid00z** [comment]
Yes, this can already be done: FreshIOC.Container.Register<IMyInterface, MyConcreteType>(); // Singleton

**Comment by moreirawebmaster** [comment]
@rid00z 

I do not think you understood the above question.

Is it possible to create the dependence injection with generics?

See: container.Register (typeof (IRepository <>), typeof (AzureRepository <>));

The entity for this repository is not informed because there are thousands.

**Comment by moreirawebmaster** [comment]
See again: 

https://stackoverflow.com/questions/15450518/how-to-register-a-generic-interface-using-tinyioc
