### ISSUE TITLE
Custom IFreshNavigationService: Need to show a MasterDetail Page along with Bottom Tabbed pages

### ISSUE THREAD

**Issue by NEETINNARENDRA** [rid00z/FreshMvvm#271]
Hello Mike, 
I checked how to create a custom navigation container from link -https://michaelridland.com/xamarin/implementing-freshmvvm-mvvm-xamarin-forms.
**I want to achieve a scenario like this : Master Detail container with Bottom Tabbed  pages** 

Also it will be helpful if you can suggest any improvements that needs to be done for the below implemenation.
But it seems the interface has changed and provided two new methods to be implemented namely 
1. SwitchSelectedRootPageModel
2. NotifyChildrenPageWasPopped

Below is my navigation class, please let me know how should i add content to these methods:

public class MasterTabbedNavigationService : MasterDetailPage, IFreshNavigationService
  {
    FreshTabbedNavigationContainer tabbedNavigationPage;
    Page _dashboard, _products, _opportunity;

    public string NavigationServiceName => throw new NotImplementedException();

    public MasterTabbedNavigationService()
    {
      SetupTabbedPage();
      CreateMenuPage("Menu");
      RegisterNavigation();
    }
    void SetupTabbedPage()
    {
      tabbedNavigationPage = new FreshTabbedNavigationContainer();
      tabbedNavigationPage.On<Android>().SetToolbarPlacement(ToolbarPlacement.Bottom);
      tabbedNavigationPage.On<Android>().SetIsSmoothScrollEnabled(false);
      tabbedNavigationPage.On<Android>().DisableSmoothScroll();
      tabbedNavigationPage.On<Android>().SetIsSwipePagingEnabled(false);
      tabbedNavigationPage.On<Android>().SetBarItemColor(Color.FromHex("#879BAA"));
      tabbedNavigationPage.On<Android>().SetBarSelectedItemColor(Color.FromHex("#2387AA"));
      _dashboard = tabbedNavigationPage.AddTab<DashboardPageModel>("Dashboard", "DashboardCP.png");
      _products = tabbedNavigationPage.AddTab<SecondPageModel>("Products", "apps.png");
      _opportunity = tabbedNavigationPage.AddTab<ItemListPageModel>("Opportunity", "OpportunityCP.png", new List<string> { "a", "b" });
      tabbedNavigationPage.BarBackgroundColor = Color.FromHex("#EBF0F5");
      tabbedNavigationPage.HeightRequest = 100;
      tabbedNavigationPage.BackgroundColor = Color.FromHex("#EBF0F5");
      this.Detail = tabbedNavigationPage;
    }

    protected void RegisterNavigation()
    {
      FreshIOC.Container.Register<IFreshNavigationService>(this);
    }

    protected void CreateMenuPage(string menuPageTitle)
    {
      var _menuPage = new ContentPage();
      _menuPage.Title = menuPageTitle;
      var listView = new Xamarin.Forms.ListView();

      listView.ItemsSource = new string[] { "Dashboard", "Products", "Opportunity", "Modal Demo" };

      listView.ItemSelected += async (sender, args) =>
      {

        switch ((string)args.SelectedItem)
        {
          case "Dashboard":
            tabbedNavigationPage.CurrentPage = _dashboard;
            break;
          case "Products":
            tabbedNavigationPage.CurrentPage = _products;
            break;
          case "Opportunity":
            tabbedNavigationPage.CurrentPage = _opportunity;
            break;
          case "Modal Demo":
            var modalPage = FreshPageModelResolver.ResolvePageModel<ItemListPageModel>();
            await PushPage(modalPage, null, true);
            break;
          default:
            break;
        }

        IsPresented = false;
      };
      IsPresented = true;
      _menuPage.Content = listView;

      Detail = tabbedNavigationPage;
      Master = new NavigationPage(_menuPage) { Title = "Menu" };
    }

    public virtual async Task PushPage(Xamarin.Forms.Page page, FreshBasePageModel model, bool modal = false, bool animated = true)
    {
      if (modal)
        await Navigation.PushModalAsync(new NavigationPage(page), animated);
      else
        await ((NavigationPage)tabbedNavigationPage.CurrentPage).PushAsync(page, animated);
    }

    public virtual async Task PopPage(bool modal = false, bool animate = true)
    {
      if (modal)
        await Navigation.PopModalAsync();
      else
        await ((NavigationPage)tabbedNavigationPage.CurrentPage).PopAsync();
    }

    public virtual async Task PopToRoot(bool animate = true)
    {
      await ((NavigationPage)tabbedNavigationPage.CurrentPage).PopToRootAsync(animate);
    }

    public Task<FreshBasePageModel> SwitchSelectedRootPageModel<T>() where T : FreshBasePageModel
    {
      **What should go here  ????**

    }

    public void NotifyChildrenPageWasPopped()
    {
    **What should go here ????**
    }
  }

**Comment by rid00z** [comment]
If you take a look at the implementations in the other navigation containers you can re-use that code. 

https://github.com/rid00z/FreshMvvm/blob/master/src/FreshMvvm/NavigationContainers/FreshMasterDetailNavigationContainer.cs#L145

https://github.com/rid00z/FreshMvvm/blob/master/src/FreshMvvm/NavigationContainers/FreshMasterDetailNavigationContainer.cs#L125
