### ISSUE TITLE
Use FreshBasePageModel and CoreMethods in View Model without adding to a container.

### ISSUE THREAD

**Issue by Surfrat** [rid00z/FreshMvvm#274]
Hi,

This is not a bug report but a software design query.

In my app I have multiple FreshMVVM pages and one that hosts a Syncfusion Rotator control for a wizard. The Init, ViewIsDisappearing page events work as expected and CoreMethods.DisplayAlert also works except for in the rotator view models.

My problem is that I wish to use the above functionality in my rotator control view models. I have inherited from FreshBasePageModel but CoreMethods is null and the page events do not get hit.

Is it possible to use the FreshMVVM functionality in my rotator view models? Do I need to add the rotator view models to a hosting container to get the correct functionality?

I have attached a sample app. 

In RotatorViewModel.cs all breakpoints are hit and the pop up is shown:
![image](https://user-images.githubusercontent.com/2066487/59433211-4f5e7e80-8de9-11e9-80e5-2f47141de8a8.png)

![image](https://user-images.githubusercontent.com/2066487/59433256-68ffc600-8de9-11e9-9cf4-f6a54c913f95.png)

In my rotator view model  RotatorPage1ViewModel.cs no breakpoints are hit and CoreMethods is null:
![image](https://user-images.githubusercontent.com/2066487/59433437-cac03000-8de9-11e9-99b0-48623441bda4.png)

I would appreciate your help.

Thanks

Mark.

[FreshMVVMSFDataGrid.zip](https://github.com/rid00z/FreshMvvm/files/3286076/FreshMVVMSFDataGrid.zip)

**Comment by libin85** [comment]
@Surfrat : Hi Mark, I believe Rotator control is a contentView, and contentview does not have any page events. And thats why they are null. It is also incorrect to do any page navigation code in the controls. Rather what you should be doing is create bindable ICommand property in the control and write the actual navigation in the viewmodel of content page that use this control.

**Comment by Surfrat** [comment]
Thank you for the feedback. I am investigating other options and have contacted Syncfusion.
