### ISSUE TITLE
Unhandled Exception:  System.Exception: <Timeout exceeded getting exception details> occurred

### ISSUE THREAD

**Issue by orassr** [rid00z/FreshMvvm#275]
`var tabs = new FreshMvvm.FreshTabbedNavigationContainer();`

`tabs.AddTab<MainTabPageModel>("Main", "icon_home.png", null);`
`tabs.AddTab<AboutTabPageModel>("About", "icon_browse.png", null);`
`MainPage = tabs;`

I am using the convention of ###PageModel  && ###Page
Still new to FreshMvvm but the error doesn't provide too much information :/

**Comment by libin85** [comment]
@orassr : The error is pretty generic and have very little information. If you dont have any logs, you might need to create a sample project and upload, so one of us can give it a try and see what exactly happens.

**Comment by rid00z** [comment]
@orassr I recently wrote a blog post that might help you solve your issue. 

I don't suspect this is a issue with FreshMvvm but more to do with your code. I'm going to close this off but reopen if you think it's FreshMvvm. 

https://michaelridland.com/xamarin/the-visual-studio-debugging-trick-that-every-xamarin-net-developer-should-know/
