### ISSUE TITLE
Master and Detail must be set before adding MasterDetailPage to a container in CustomImplementedNav

### ISSUE THREAD

**Issue by swapnil591** [rid00z/FreshMvvm#277]
[AndroidRuntime] android.runtime.JavaProxyThrowable: System.InvalidOperationException: Master and Detail must be set before adding MasterDetailPage to a container
[AndroidRuntime]   at Xamarin.Forms.MasterDetailPage.OnParentSet () [0x00018] in <0517b88d5a634c788479622a1afed82c>:0 
[AndroidRuntime]   at Xamarin.Forms.Element.set_Parent (Xamarin.Forms.Element value) [0x0008e] in <0517b88d5a634c788479622a1afed82c>:0 
[AndroidRuntime]   at Xamarin.Forms.Application.set_MainPage (Xamarin.Forms.Page value) [0x0005f] in <0517b88d5a634c788479622a1afed82c>:0 
[AndroidRuntime]   at Mobility.ViewModels.WelcomeViewModel.NavigateToMainPage () [0x001db] in <a68c78b3e2a24028b5d5a4d801fef25e>:0 
[AndroidRuntime]   at Mobility.ViewModels.WelcomeViewModel.<.ctor>b__15_0 () [0x00062] in <a68c78b3e2a24028b5d5a4d801fef25e>:0 
[AndroidRuntime]   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <5660c95f3e294efb951e3063855a2386>:0 
[AndroidRuntime]   at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <60186bcdff564d048e04f909c636a810>:0 
[AndroidRuntime]   at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <60186bcdff564d048e04f909c636a810>:0 
[AndroidRuntime]   at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <60186bcdff564d048e04f909c636a810>:0 
[AndroidRuntime]   at (wrapper dynamic-method) Android.Runtime.DynamicMethodNameCounter.50(intptr,intptr)
[AndroidRuntime] 	at mono.java.lang.RunnableImplementor.n_run(Native Method)
[AndroidRuntime] 	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
[AndroidRuntime] 	at android.os.Handler.handleCallback(Handler.java:790)
[AndroidRuntime] 	at android.os.Handler.dispatchMessage(Handler.java:99)
[AndroidRuntime] 	at android.os.Looper.loop(Looper.java:164)
[AndroidRuntime] 	at android.app.ActivityThread.main(ActivityThread.java:6494)
[AndroidRuntime] 	at java.lang.reflect.Method.invoke(Native Method)
[AndroidRuntime] 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
[AndroidRuntime] 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by libin85** [comment]
@swapnil591 : Appreciate if you can give a bit more information. Probably some code so that we can see what exactly is happening

**Comment by swapnil591** [comment]
public CustomImplementedNav()
        {
            NavigationServiceName = "CustomImplementedNav";
            SetupTabbedPage();
           CreateMenuPage("Menu");
           RegisterNavigation();
        }

        void SetupTabbedPage()
        {

			_twoPage = FreshPageModelResolver.ResolvePageModel<TwoViewModel>();
			_navTwo = new FreshNavigationContainer(_twoPage, "Two");

            _threePage = FreshPageModelResolver.ResolvePageModel<ThreeViewModel>();
			_navThree = new FreshNavigationContainer(_threePage, "Three");

			var tabbedNavigation = new FreshTabbedNavigationContainer();
            tabbedNavigation.On<Xamarin.Forms.PlatformConfiguration.Android>().SetToolbarPlacement(ToolbarPlacement.Bottom);
            tabbedNavigation.AddTab<ConfrimTripViewModel>("Confirm", "confirmedtrips.png", "CONF");
            tabbedNavigation.AddTab<ConfrimTripViewModel>("Proposal", "proposaltrips.png", "PAST");
            tabbedNavigation.AddTab<ConfrimTripViewModel>("Past", "pasttrips.png", "QUOTE");
            
            this.Detail = _tabbedNavigationPage;
            
        }

        protected void RegisterNavigation()
        {
            FreshIOC.Container.Register<IFreshNavigationService>(this, NavigationServiceName);
        }

        protected void CreateMenuPage(string menuPageTitle)
        {
            var _menuPage = new ContentPage();
            _menuPage.Title = menuPageTitle;
            var listView = new ListView();

            listView.ItemsSource = new string[] { "One", "Two", "Three" };



            listView.ItemSelected += (sender, args) =>
          {

              switch ((string)args.SelectedItem)
              {

                  case "One":
                      this.Detail = _tabbedNavigationPage;
                      break;

                  case "Two":
                      this.Detail = _navTwo;
                      break;

                  case "Three":
                      this.Detail = _navThree;
                      break;
                  default:
                      break;
              }

              IsPresented = false;
          };

            _menuPage.Content = listView;
            
             Master = new NavigationPage(_menuPage) { Title = "Menu" };

            

        }
