### ISSUE TITLE
Can not change  push  animation in the android platform？ I need a custom animation！

### ISSUE THREAD

**Issue by liuzhenLz** [rid00z/FreshMvvm#283]

**Comment by libin85** [comment]
page transitions are not available in Xamarin forms nor in FreshMvvm. You will need to do that yourself, or use any third party nuget library.Jut google "page transitions xamarin forms" and you should plenty of resources to help you get started. I am closing this issue.

**Comment by liuzhenLz** [comment]
OK thank you ! I get it. buy the way, in freshMvvm should add a push model animation，I can push a PR in freshMvvm.

**Comment by liuzhenLz** [comment]
just can degsin to freshMvvmCore and freshMvvmEx two visions, haha

**Comment by libin85** [comment]
@liuzhenLz : I dont personally agree adding the animation to the core library but agree with the idea to have in freshmvvmextension

**Comment by libin85** [comment]
@liuzhenLz : Just so you are aware, there is another library called https://github.com/XAM-Consulting/FreshEssentials. Have a look, it has many utilities too
