### ISSUE TITLE
Nested navigation inside a Modal does not work

### ISSUE THREAD

**Issue by therealjohn** [rid00z/FreshMvvm#29]
`CoreMethods.PushPageModel<T>` does not navigate as expected in a Modal page. 

Here is a video of the behavior: http://screencast.com/t/gErUL9c2h

The basic navigation wraps any new Modal in a NavigationPage, which is great. However, when trying to navigate to pages while that Modal is displayed, the pages are pushed underneath (in the other parent NavigationPage). 

I have been playing with this and investigating my options. Suggestions are welcome.

**Comment by jfversluis** [comment]
That is why there is a modal parameter that you can set to try while calling this method?

**Comment by therealjohn** [comment]
@jfversluis 

I might be confused. Using the modal paramater is just a toggle to cause a Modal to be used, not to tell that you are navigating inside a modal. If you were to just pass a true, it would display another modal on top of this one. Instead, I want to be able to navigate forward inside the NavigationPage stack that is already wrapping this Modal. 

See [this](https://github.com/rid00z/FreshMvvm/blob/master/src/FreshMvvm/FreshNavigationContainer.cs#L16-L26).

**Comment by rid00z** [comment]
I have a solution for this that I'm working on now and will have done in
next days.

The solution is based on having multiple Navigation services.


On Sunday, 10 January 2016, John Miller <notifications@github.com> wrote:

> @jfversluis <https://github.com/jfversluis>
>
> I might be confused. Using the modal paramater is just a toggle to cause a
> Modal to be used, not to tell that you are navigating inside a modal. If
> you were to just pass a true, it would display another modal on top of this
> one. Instead, I want to be able to navigate forward inside the
> NavigationPage stack that is already wrapping this Modal.
>
> See this
> <https://github.com/rid00z/FreshMvvm/blob/master/src/FreshMvvm/FreshNavigationContainer.cs#L16-L26>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rid00z/FreshMvvm/issues/29#issuecomment-170280464>.
>


-- 

*Michael Ridland | Technical Director | Xamarin MVP*

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com

**Comment by therealjohn** [comment]
@rid00z That is great to hear. Thanks for your effort on this, loving it!

**Comment by rid00z** [comment]
This is solved in the current code base and will be in next release.
