### ISSUE TITLE
Master Details my own design 

### ISSUE THREAD

**Issue by osamaelhosany** [rid00z/FreshMvvm#291]
Hi, Guys 
I need your help as I am new with FreshMvvm 
How do I create my own design for the master page something like this?
![flyout-annotated](https://user-images.githubusercontent.com/17553076/67636133-13c6db80-f8d6-11e9-9fb0-dee06dc13a5a.png)

**Comment by LeoJHarris** [comment]
Take a look at this comment: https://github.com/rid00z/FreshMvvm/issues/37#issuecomment-194536483 this is pretty much what you want to do.

In the CreateMenuPage method you can initialize your custom menu page and assign that as the Master. For that youl need make your own class that extends `FreshMasterDetailNavigationContainer` and use that as the Container on App.cs
