### ISSUE TITLE
packages.config missing from sample Droid project

### ISSUE THREAD

**Issue by dlee1067** [rid00z/FreshMvvm#3]
It looks like the packages.config file is missing from the FreshMvvmSampleApp.Droid project.

**Comment by wcoder** [comment]
`packages.config` correctly contains on here: 

https://github.com/rid00z/FreshMvvm/blob/master/samples/FreshMvvmSampleApp/Droid/FreshMvvmSampleApp.Droid.csproj#L80

https://github.com/rid00z/FreshMvvm/blob/master/samples/FreshMvvmSampleApp/Droid/packages.config
