### ISSUE TITLE
[IoC] Constructor Injection: IEnumerable of services

### ISSUE THREAD

**Issue by hypervtechnics** [rid00z/FreshMvvm#300]
It is not possible at the moment to request all registered services of one type. At least during my tests. Although according to TinyIoc this is possible.

Want I want to do:
```csharp
// In the container initialization
FreshIOC.Container.Register<IModule, ImplementationOne>();
FreshIOC.Container.Register<IModule, ImplementationTwo>();
FreshIOC.Container.Register<IModule, ImplementationThree>();
FreshIOC.Container.Register<IService, SomeService>();

// The class 
public class SomeService
{
    public SomeService(IEnumerable<IModule> modules)
    {
        // modules contains instances of ImplementationOne, ImplementationTwo and ImplementationThree
    }
    // ...
}
```

**Comment by berhir** [comment]
You can use `RegisterMultiple` (see [TinyIoC wiki](https://github.com/grumpydev/TinyIoC/wiki/Registration---lifetimes)).

> Multiple implementations of the same baseclass/interface can be registered using RegisterMultiple. This can be useful if you have a marker interface/shared base class and you want to register multiple implementations to retrieve later using ResolveAll or using an IEnumerable dependency:

```
container.RegisterMultiple<IMyMarkerInterface>(new[] { typeof(MyImplementationClass1), typeof(MyImplementationClass2) });
```
