### ISSUE TITLE
[Android] FreshTabbedNavigationContainer "jump" home on tab click

### ISSUE THREAD

**Issue by ivarlovlie** [rid00z/FreshMvvm#315]
On iOS, regardless of where i am in the navigationstack, when i click on the tab that "represents" the top level page for my current navigation stack i am popped to the top level page. This is not the case with android, instead i have to pop multiple times to get to the mainpage, is this intended or am i doing something wrong?

**Comment by munkii** [comment]
@ivarlovlie I don't know if you have already tried but you are more likely to get a response to this question on StackOverflow. If I knew the answer I'd offer to answer on SO but I've never used the FreshTabbedNavigationContainer.

**Comment by ivarlovlie** [comment]
Thanks @munkii, asked on SO here: https://stackoverflow.com/questions/63567176.
