### ISSUE TITLE
Hamburger Menu is displayed in the Content Page in Landscape Orientation - Android

### ISSUE THREAD

**Issue by Mushtaq123** [rid00z/FreshMvvm#323]
I am facing an issue that the Hamburger Menu is displayed in the Content Page when the device Orientation is Landscape. 

We have the Master-Detail page as a root page and the master page is created by following the below approach from the code behind.

```
Master = FreshMvvm.FreshPageModelResolver.ResolvePageModel<ProfilePageModel>();
Detail = new NavigationPage(FreshMvvm.FreshPageModelResolver.ResolvePageModel<MenuPageModel>());
```
### Screenshot for reference:
![image](https://user-images.githubusercontent.com/22950250/109272030-57b55200-7836-11eb-92be-e5e4c98720f9.png)

### Expected Behaviour:
The hamburger icon should not be displayed on the content page whatever the device orientation since it is applicable for Master-Detail Page.

### Actual Behaviour:
The hamburger icon is displaying on the content page when the device orientation is Landscape.

Kindly help me to sort out this issue.

**Comment by rid00z** [comment]
In this case I would recommend the FreshMaster detail. using https://github.com/rid00z/FreshMvvm#master-detail---built-in
