### ISSUE TITLE
masterDetail doesnt display on all pages

### ISSUE THREAD

**Issue by EmilAlipiev** [rid00z/FreshMvvm#36]
Hi

I tried to create a masterdetail page using freshmvvm as below. but It looks like that it only display on start up page, when I navigate to any other page that is not the list of MasterPage, it will not be visible

     public App()
        {
 
            // The root page of your application
            LoadMasterDetail();
        }

    public void LoadMasterDetail()
        {
            var masterDetailNav = new FreshMasterDetailNavigationContainer();
            masterDetailNav.Init("Menu", "Menu.png");
            masterDetailNav.AddPage<Page1PageModel>("Page1", null);
            masterDetailNav.AddPage<Page2PageModel>("Page2", null);
            masterDetailNav.AddPage<Page3PageModel>("Page3", null);
            MainPage = masterDetailNav;
        }

So according to above if I have page4Page and Page4PageModel which I am navigating through somewhere else when I am on this page, I dont see any masterdetail container. Is this supposed to be like that? 

2nd thing, It executes through each and every pagemodel at the application start. This means if I have some heavy operation in any pageModel, this will reduce application start time. Is there anyway to prevent this?

thanks.

**Comment by EmilAlipiev** [comment]
Beside the problem mentioned above, MasterDetailPage is only displayed once and you can never display it again if you navigate to any other page. Because it doesnt actually implement a real navigation page. it takes the first as a primary navigation page. for example. Contacts Page is primary navigation page here. But once you go to ContactDetail page from Contacts page. If you use back button or any other navigation to Contacts page, you wont able to see mastedetailpage. 

```
var masterDetailNav = new FreshMasterDetailNavigationContainer ();
masterDetailNav.Init ("Menu");
masterDetailNav.AddPage<ContactListPageModel> ("Contacts", null);
masterDetailNav.AddPage<QuoteListPageModel> ("Pages", null);
MainPage = masterDetailNav;
```

**Comment by rid00z** [comment]
I've taken a look and there doesn't seem to be any issue, it works as desired. Can you give some details on your exact issue maybe a screenshot? 

In regards to loading once a page is opened you can use the appearing event on the page.
