### ISSUE TITLE
Recommended way to bind page events to a page model - MessagingCenter?

### ISSUE THREAD

**Issue by rupe120** [rid00z/FreshMvvm#40]
I've been trying to understand the best way to bind events like `Entry.Completed` to logic in the page model, and conversely having the page model direct page control behavior like `Entry.Focus()`. 

It seems like a good solution for the `Completed` event is to wire the event(s) directly in the page code behind file, and in those events call `MessagingCenter.Send()` with a corresponding `MessagingCenter.Subscribe()` in the page model.

Then doing just the opposite to trigger `Entry.Focus()` in the page. 

Is this pretty much best practice for things like this? Or is there a more binding-y way to do this?

**Comment by rupe120** [comment]
I found a nice answer to the Event to Command question. @corradocavalli has a fantastic package of behaviors including an `EventToCommand` behavior

[https://github.com/corradocavalli/Corcav.Behaviors](https://github.com/corradocavalli/Corcav.Behaviors)

**Comment by rid00z** [comment]
Hi @rupe120 

You might also want to check out this.. http://www.michaelridland.com/xamarin/xaml-attached-properties-tricks-in-xamarin-forms/
