### ISSUE TITLE
Back button on iOS sometimes takes name of previous page instead of 'Back'

### ISSUE THREAD

**Issue by allenmoatallen** [rid00z/FreshMvvm#41]
As the title says we are seeing an issue where the **< Back** button on iOS will sometimes change to **< Previous Page Name** instead of Back.

**Comment by rid00z** [comment]
This is a Xamarin.Forms things, it's a setting in the NavigationPage, NavigationPage.SetBackButtonTitle. 

This shouldn't be change by anything in FreshMvvm, correct?

**Comment by allenmoatallen** [comment]
Correct, I am not modifying that at all. It only happens on iOS and wasn't sure if I should post here or move to Xamarin.Forms.

**Comment by rid00z** [comment]
Just have a look into the settings on NavigationPage you can set them directly or set them in Xaml by attached properties. 

If you do find an issue with Fresh then re-open the issue.

**Comment by allenmoatallen** [comment]
@rid00z Just wanted to follow up. It appears the Xamarin.Forms behavior is to use the name of the previous page for the back button title unless the child view's title is too long.
