### ISSUE TITLE
Calling PushPageModel outside of page model

### ISSUE THREAD

**Issue by OpticNectar** [rid00z/FreshMvvm#43]
How can I call `PushPageModel` or something similar outside of a page model? There are times I need to call it from a menu that has it's own View Model that does not inherit and cannot inherit from `FreshBasePageModel`. I'm using http://xam-consulting.com/slideoverkit-xamarin-forms/ in case you are wondering.

**Comment by rid00z** [comment]
So you might need to get the navigation service out of the IOC container
and push it yourself?

It kind of depends. what type of navigation do you have?




On Friday, 19 February 2016, OpticNectar <notifications@github.com> wrote:

> How can I call PushPageModel or something similar outside of a page
> model? There are times I need to call it from a menu that has it's own View
> Model that does not inherit and cannot inherit from FreshBasePageModel.
> I'm using http://xam-consulting.com/slideoverkit-xamarin-forms/ in case
> you are wondering.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rid00z/FreshMvvm/issues/43>.
>


-- 

*Michael Ridland | Technical Director | Xamarin MVP*

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com

**Comment by OpticNectar** [comment]
Is there an example of how to do that somewhere? I haven't worked with IOC containers much, and i'm not sure how to go about that.

**Comment by rid00z** [comment]
@OpticNectar  

It really depends on your overall navigation. 

var navService = FreshMvvm.FreshIOC.Container.Resolve<IFreshNavigationService> (FreshMvvm.Constants.DefaultNavigationServiceName);
            var page = FreshPageModelResolver.ResolvePageModel<MyPageModel> ();
            navService.PushPage (page, null);

@OpticNectar please feel free to email me michael@xam-consulting.com

**Comment by JoshuaNovak919** [comment]
@rid00z That seemed to have worked perfectly. Thanks!!

**Comment by oddbear** [comment]
The code there does not work for me.
The case is that i try to push a page from a notification and navigate to page.

Case 1: Getting notification, pressing home, open notification. Does not work.
Case 2: Getting notification, have app open, open notification. OK.
Case 3: Getting notification, pressing back until app closes, open notification. OK.

**Comment by jamesatgithub** [comment]
@rid00z I have similar question like the one in this thread: 
1. my app main page is a MasterDetail which uses FreshMvvmMasterDetailNavigation already
2. when app not running, and a push notification coming, I want the app to open a specific Detail page still with the Master menu at right side as normal app launch does

how can I implement this with FreshMvvm and/or forms navigation service?
