### ISSUE TITLE
 FRESHMVVM MASTERDETAILPAGE EXECUTES VIEWMODELS

### ISSUE THREAD

**Issue by EmilAlipiev** [rid00z/FreshMvvm#44]
when you have FreshMasterDetailNavigationContainer as below, it will execute through each PageModel (ViewModel) init and constructor and if you have some initial data loading your view, this will be very expensive. Is there a way to prevent this? Otherwise for me Freshmvvm is no use. 

thanks.

     var masterDetailNav = new FreshMasterDetailNavigationContainer();
            masterDetailNav.Init("Menu", "Menu.png");
            masterDetailNav.AddPage<page1PageModel>("page1", null);
            masterDetailNav.AddPage<page2PageModel>("page2", null);
             masterDetailNav.AddPage<page3PageModel>("page3", null);
            masterDetailNav.AddPage<page4PageModel>("page4", null);
            masterDetailNav.AddPage<page5PageModel>("page5", null);

**Comment by rid00z** [comment]
You can use the Appearing event on the page. 

The Init method is working as desired which is that it's being called during creation and to be used to pass in init data.

**Comment by EmilAlipiev** [comment]
Hi Michael, 

I would to reopen this issue because I believe this is a serious problem with Freshmvvm and it makes freshmvvm for tabbed page and masterdetail etc quite useless. We cant consider Appearing event as a solution, it has totally different purpose. It makes app quite inefficient if we load the data every time navigating back and forth. even it loads when switching between apps, as the name said whenever screen appears.
Please let me know your thoughts please.

thanks,

Emil
