### ISSUE TITLE
Opening sample solution in Xamarin Studio fails with errors

### ISSUE THREAD

**Issue by buzzware** [rid00z/FreshMvvm#46]
![image](https://cloud.githubusercontent.com/assets/28285/13546379/23fdf4f6-e2e7-11e5-9a66-52c7f1f2978b.png)

I simply git cloned the repository then tried to open the sln with the latest Xamarin Studio

**Comment by buzzware** [comment]
As pointed out in https://github.com/rid00z/FreshMvvm/pull/39, the sln file in samples is confusing and should be removed. 

Users should ignore that one and just open src/FreshMvvm.sln

**Comment by rid00z** [comment]
Strange, thought that sln was deleted!


On Saturday, 5 March 2016, buzzware <notifications@github.com> wrote:

> As pointed out in #39 <https://github.com/rid00z/FreshMvvm/pull/39>, the
> sln file in samples is confusing and should be removed.
>
> Users should ignore that one and just open src/FreshMvvm.sln
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rid00z/FreshMvvm/issues/46#issuecomment-192606887>.
>


-- 

*Michael Ridland | Technical Director | Xamarin MVP*

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com
