### ISSUE TITLE
internal CurrentNavigationServiceName makes custom navigation pages hard to implement

### ISSUE THREAD

**Issue by ewan-fraedom** [rid00z/FreshMvvm#50]
All the navigation controls rely on being able to read the service name from the page model. But this is not exposed to custom implementations of IFreshNavigationService. this makes it hard to create custom navigators which work with the CoreMethods pop and push methods

**Comment by EmilAlipiev** [comment]
when you have parameters in the constructor, It doesnt work I think. Code below will fail but If I remove userdialog parameter, It will work. not sure if there is a solution for this.

I have this implemented
```

   var page = FreshPageModelResolver.ResolvePageModel<LoginPageModel>(Client);
            var basicNavContainer = new FreshNavigationContainer(page);
            MainPage = basicNavContainer;

 public LoginPageModel(IUserDialogs userDialogs)
        {
}
```
