### ISSUE TITLE
How to implement PropertyChanged in pagemodels inherited from FreshBasePageModel?

### ISSUE THREAD

**Issue by fcogutierrez** [rid00z/FreshMvvm#52]
I would like to avoid Fody, and I would like to reuse the PropertyChangedEventHandler PropertyChanged that there is in FresBasePageModel.

How can I do this?

**Comment by rid00z** [comment]
Yes there's a method to raise the event. Let me know if you have issues, it should be good.

**Comment by fcogutierrez** [comment]
Yes, sorry, you have to call to RaisePropertyChanged method.

Thanks a lot for your work, congratulations!! I am migrating my current project architecture to this framework :-).
