### ISSUE TITLE
Cant two pages have the same PageModel?

### ISSUE THREAD

**Issue by fcogutierrez** [rid00z/FreshMvvm#54]
I have SearchItemsPage and ItemsLookupPage. I want that both of them use the same pagemodel (ItemsPageModel).

Is this possible to "jump" the framework convention for exceptional cases?

Thanks :).

**Comment by rid00z** [comment]
Yes, you can. :)

Task PushPageModel<T, TPage> (object data, bool modal = false) where T : FreshBasePageModel

**Comment by fcogutierrez** [comment]
@rid00z but how can I specify the Page to push? Because I have two different pages for the same PageModel, but I want to push an specific one.

Just waiting for your reply. Thanks!! :)

**Comment by fcogutierrez** [comment]
@rid00z, I don't see any solution for this. What can I do? I just finished the migration to this MVVM framework but I don't find how to do this.

**Comment by rid00z** [comment]
Hi, this feature was added in 1.0.1.

http://www.michaelridland.com/xamarin/announcing-freshmvvm-1-0-1-release/

`Task PushPageModel<T, TPage> (object data, bool modal = false) where T : FreshBasePageModel where TPage : Page;`

**Comment by fcogutierrez** [comment]
Ah perfect, just updated to latest version. Thanks a lot :).
