### ISSUE TITLE
Release notes?

### ISSUE THREAD

**Issue by MBrekhof** [rid00z/FreshMvvm#55]
I noticed several new releases last month, I like that! Are there any release notes to find out what got changed/fixed/added?

**Comment by rid00z** [comment]
I'm planning to setup a website with this type of information, primarily the last update was:
[http://www.michaelridland.com/xamarin/announcing-freshmvvm-1-0-1-release/](http://www.michaelridland.com/xamarin/announcing-freshmvvm-1-0-1-release/)

**Comment by EmilAlipiev** [comment]
Site is great idea but It would be also nice to have titles of changes on nuget, I believe :)
