### ISSUE TITLE
Create NuGet package that does not include FreshIOC

### ISSUE THREAD

**Issue by vb2ae** [rid00z/FreshMvvm#56]
Fresh IOC is not compatible with UWP apps.  Please create a FreshMVVM package that does not include FreshIOC for people who what to use another IOC container.

**Comment by rid00z** [comment]
I will take a look at this tomorrow. Do have any details on why it doesn't work?

**Comment by vb2ae** [comment]
Sorry looks like with the latest nuget package ir is working.
