### ISSUE TITLE
Navigation from Master page

### ISSUE THREAD

**Issue by fcogutierrez** [rid00z/FreshMvvm#57]
Hello,

I have a MenuPage (and MenuPageModel) as Master page. This menu has a list of options with some commands binded.

How can I do for do the navigation (PushAsync) from MenuPageModel? Here is my code.

            var menuPage = FreshPageModelResolver.ResolvePageModel<MenuPageModel>();
            this.Master = menuPage;

            var homePage = FreshPageModelResolver.ResolvePageModel<HomePageModel>();
            this.Detail = new FreshNavigationContainer(homePage);

Thanks.

**Comment by rid00z** [comment]
FreshMvvm has a built in master detail Navigation, you can use that or take
the code from that and modify.

Thanks


On Tuesday, 29 March 2016, fcogutierrez <notifications@github.com> wrote:

> Hello,
>
> I have a MenuPage (and MenuPageModel) as Master page. This menu has a list
> of options with some commands binded.
>
> How can I do for do the navigation (PushAsync) from MenuPageModel? Here is
> my code.
>
>         var menuPage = FreshPageModelResolver.ResolvePageModel<MenuPageModel>();
>         this.Master = menuPage;
>
>         var homePage = FreshPageModelResolver.ResolvePageModel<HomePageModel>();
>         this.Detail = new FreshNavigationContainer(homePage);
>
> Thanks.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rid00z/FreshMvvm/issues/57>
>


-- 

*Michael Ridland | Technical Director | Xamarin MVP*

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com

**Comment by fcogutierrez** [comment]
Yes @rid00z , I have tried, but the items of my menu have some icons and some customization. I don't want a simple list in the Master side.

Thanks.

**Comment by rid00z** [comment]
Please use the built in as an example and implement you own navigation
service.

Thanks


On Tuesday, 29 March 2016, fcogutierrez <notifications@github.com> wrote:

> Yes @rid00z <https://github.com/rid00z> , I have tried, but the items of
> my menu have some icons and some customization. I don't want a simple list
> in the Master side.
>
> Thanks.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/rid00z/FreshMvvm/issues/57#issuecomment-202836170>
>


-- 

*Michael Ridland | Technical Director | Xamarin MVP*

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com

**Comment by rid00z** [comment]
@fcogutierrez 

Here's what you might be trying to do.... basically you can get the HomePageModel instance, and pass it into the MenuPageModel, from that instance you can call CoreMethod.PushPageModel. 

```
var homePage = FreshPageModelResolver.ResolvePageModel<HomePageModel>();
this.Detail = new FreshNavigationContainer(homePage);
var homePageModel = homePage.GetModel();

var menuPage = FreshPageModelResolver.ResolvePageModel<MenuPageModel>(homePageModel);
this.Master = menuPage;

homePageModel.CoreMethods.PopToRoot();
homePageModel.CoreMethods.PushPageModel<SecondLevelPage>();

```

**Comment by fcogutierrez** [comment]
Good solution, thanks a lot @rid00z

**Comment by EmilAlipiev** [comment]
What is PopToRoot() doing? I couldnt find any explanation for it.

**Comment by rid00z** [comment]
It's pops all pages in current navigation stack.

**Comment by mze666** [comment]
Thank you @rid00z  for your great work.
I use the code you mentioned earlier and it works fine but a problem is master page still showing after clicking on a button that shows another page on detail section.
how can i hide master menu?

**Comment by codegrue** [comment]
Any solution for hiding the menu after the click?

**Comment by codegrue** [comment]
This worked but it feels like a hack. Would like to know if there is support in FreshMvvm itself:

I App.cs, add a property to expose the main (details) stack:

```
        private FreshMasterDetailNavigationContainer _mainStack;
        public FreshMasterDetailNavigationContainer MainStack{
            get {
                return _mainStack;
            }
        }
```

Then in menu view model, you can access this to call the native "IsPresented" property:

```
        public Command MenuCommand
        { 
            get => new Command(async () => { 
                await CoreMethods.PopToRoot(true);
                await CoreMethods.PushPageModel<DetailsViewModel>();
                (Application.Current as MyApp.App).MainStack.IsPresented = false;
            });
        }
```
