### ISSUE TITLE
Unable to resolve type: FreshMvvm.IFreshNavigationService

### ISSUE THREAD

**Issue by jbravobr** [rid00z/FreshMvvm#65]
When i try to Push a new Page

**Comment by rid00z** [comment]
Did you solve this?

**Comment by jbravobr** [comment]
Yes! My problem was my implementation. I start my App with an "Content Page" (a Login page), when user hits OK with the correct information, than I start a new Tabbed Page. When I trie to fire with the "Push" I got the error. So I use the option to switch context and now it's work. My doubt is how can I remove from the context the login page.

**Comment by gjhdigital** [comment]
I get the same error. Im using FreshMvvm 2.0.1.
I was following the steps on:
https://github.com/rid00z/FreshMvvm#switching-out-navigationstacks-on-the-xamarinforms-mainpage

I'm trying to create a Login pagemodel using FreshNavigationContainer then navigate to a masterdetail FreshMasterDetailNavigationContainer by calling:
CoreMethods.SwitchOutRootNavigation(NavigationContainerNames.MasterDetailContainer);
from inside a button Command in the Login pagemodel
