### ISSUE TITLE
full exception stack information

### ISSUE THREAD

**Issue by EmilAlipiev** [rid00z/FreshMvvm#66]
FreshMVVM is easy to use and supposed to speed up development time but actually more I use, I feel like it is my hump and it slows me down. everytime something is wrong on xaml or in viewmodel freshmvvm will popout this message. FreshTinyIoC.TinyIoCResolutionException: Unable to resolve type: blablaPage.xaml

 I need to find the error debugging line by line if it is in xaml, i need to find out by removing things and try each label, button etc. Is there no possibility to enhance this situation with full exception information?

**Comment by xorch** [comment]
Check if you don't have syntax errors in XAML, that's usually a problem.

**Comment by rid00z** [comment]
All you need to do is look at the application output and the exception will
be there.

Also xamlc would help with this.


On Thursday, 28 April 2016, hal9k2 <notifications@github.com> wrote:

> Check if you don't have syntax errors in XAML, that's usually a problem.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/rid00z/FreshMvvm/issues/66#issuecomment-215536005>
>


-- 

*Michael Ridland | Technical Director | Xamarin MVP*

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com

**Comment by rid00z** [comment]
I will also look at bubbling up this error.



On Thursday, 28 April 2016, Michael Ridland <rid00z@gmail.com> wrote:

>
> All you need to do is look at the application output and the exception
> will be there.
>
> Also xamlc would help with this.
>
>
> On Thursday, 28 April 2016, hal9k2 <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
>> Check if you don't have syntax errors in XAML, that's usually a problem.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/rid00z/FreshMvvm/issues/66#issuecomment-215536005>
>>
>
>
> --
>
> *Michael Ridland | Technical Director | Xamarin MVP*
>
> XAM Consulting - Mobile Technology Specialists
>
> www.xam-consulting.com
>
> Blog: www.michaelridland.com
>
>
>
>

-- 

*Michael Ridland | Technical Director | Xamarin MVP*

XAM Consulting - Mobile Technology Specialists

www.xam-consulting.com

Blog: www.michaelridland.com

**Comment by matthews-jca** [comment]
For reference, I've had similar issues with this but simply hit continue twice in VS to crash the app and let the exception get dumped out to the output window. The rest of the stack trace will usually point to a line and better error.
