### ISSUE TITLE
Navigate to FreshTabbedNavigationContainer without pushing a modal

### ISSUE THREAD

**Issue by fcogutierrez** [rid00z/FreshMvvm#67]
How can I navigate to a tabbed page without pushing a modal?

I am doing this:

    var tabbedNavigation = new FreshTabbedNavigationContainer ("secondNavPage");
    tabbedNavigation.AddTab<ContactListPageModel> ("Contacts", "contacts.png", null);
    tabbedNavigation.AddTab<QuoteListPageModel> ("Quotes", "document.png", null);

    await CoreMethods.PushNewNavigationServiceModal(tabbedNavigation);

But I don' want to navigate to this tabbed page in a Modal. Is this possible to do only push?

Thanks.

**Comment by fcogutierrez** [comment]
Any way to do this?

**Comment by rid00z** [comment]
Fresh doesn't support it because it's not within the platforms UI design guidelines and last time I checked it look funny on iOS anyway. 

Why not use Modal with a close button?

**Comment by EmilAlipiev** [comment]
wow old post here but just in case anybody else looking for a solution. You can create a simple xamarin tabbedpage and navigate to it. it is no difference.
