### ISSUE TITLE
Using Rg.Plugins.Popup with FreshMvvM

### ISSUE THREAD

**Issue by homerokzam** [rid00z/FreshMvvm#78]
I want to use Rg.Plugins.Popup component with FreshMvvm. To trigger the popup, I have to call the method Rg.Plugins.Popup.Extensions.NavigationExtension.PushPopupAsync through  this.CurrentPage.Navigation class. But I can not use the features of the Model Page. can anybody help me?

sample:
              CartaoPopUpView view = new CartaoPopUpView ();
              await this.CurrentPage.Navigation.PushPopupAsync (view);

Thanks,
Homero

**Comment by rid00z** [comment]
Hi, I think it's likely to be a issue with the PopUps, not to do with FreshMvvm.

**Comment by homerokzam** [comment]
Ok. Thank you.

Congratulations on FreshMvvm. The best mvvm library I have ever used!

**Comment by KathirveluM** [comment]
Hi @rid00z , 
We have posted the same query in [https://github.com/rotorgames/Rg.Plugins.Popup/issues/27](url) and suggested to write a wrapper for this approach. 
Please suggest on writing a wrapper for using the plugin with Fresh MVVM framework.

**Comment by EmilAlipiev** [comment]
I mixed both plugins. I am calling popup on the xaml.cs files. it is a bit messy but yet working. I wish that freshmvvm could work with this popup. that will be really powerful
