### ISSUE TITLE
PushNewNavigationServiceModal not working anymore ?

### ISSUE THREAD

**Issue by samukbg** [rid00z/FreshMvvm#79]
Hi all,

I am new to FreshMVVM, i am using version 2.1.0 and since i've updated for the new version of Xamarin (6.0) and Xamarin.Forms (2.3.0.49) the PushNewNavigationServiceModal method is not working anymore. There is no errors or warnings it just doesn't works, but the PushPageModel method is working fine.

Thanks in advance,
Samuel

**Comment by rid00z** [comment]
Hi @samukbg, I cannot reproduce this issue. :(

**Comment by rid00z** [comment]
@samukbg If you can provide a sample reproduction of this issue in a project, please re-open this issue.

**Comment by samukbg** [comment]
@rid00z Sorry for the late answer. Here is the code :
`if (Device.RuntimePlatform == Device.Android)
						{
							var lessonsPage = FreshPageModelResolver.ResolvePageModel<LessonsPageModel>();
							var lessonsPageNavigationPage = new FreshNavigationContainer(lessonsPage);
							lessonsPageNavigationPage.BarTextColor = Color.White;
							lessonsPageNavigationPage.ToolbarItems.Add(new ToolbarItem("Test", "icn_btn_close.png", async () =>
							{
								await CoreMethods.PopPageModel(true, true);
							}));
                            await CoreMethods.PushNewNavigationServiceModal(lessonsPageNavigationPage, new FreshBasePageModel[] { lessonsPage.GetModel() }, true);
                        }`

When the last await method is called the new page is not been called with no error or warnings.
