### ISSUE TITLE
can't resolve type only in Release Build

### ISSUE THREAD

**Issue by mathewgrabau** [rid00z/FreshMvvm#8]
I am unable to resolve a type in my Release configuration. The Debug work is functioning, but the Release only works if I remove the controls that have custom renderers.

The specific problem that I am having is a System.IO.FileNotFound exception on the namespace. The exception is being thrown when trying to PushModelAsync

**Comment by rid00z** [comment]
Hi @mathewgrabau 

FreshMvvm doesn't do any file IO so I'm not sure this is the issues. Can you put this into a sample project that reproduces the issue?

**Comment by mathewgrabau** [comment]
I apologize - I spent ages on this, and in the end it turns out the Xaml was failing because the assembly had a typo in the x:local declaration. Upper case vs lower case. It also explained why it worked when the control was created in code-behind.

I will close the issue since it was entirely unrelated to FreshMVVM. However, thank you for the nice library, it made building my most recent application a snap.
