### ISSUE TITLE
Rg.Plugins.Popup to use in FreshMvvM

### ISSUE THREAD

**Issue by KathirveluM** [rid00z/FreshMvvm#88]
Hi,

We want to use the Rg.Plugins.Popup component with FreshMvvm framework. To trigger the popup, We have to call the PushPopupAsync through Navigation class. 

The same is discussed in the below post as well and then we posted the same to Rg.Plugins.Popup Component forums and suggested as "to write a wrapper for this approach".
https://github.com/rid00z/FreshMvvm/issues/78

Please suggest on writing a wrapper to use this plugin with Fresh MVVM framework.

**Comment by rid00z** [comment]
You could use https://github.com/XAM-Consulting/SlideOverKit and then you wouldn't need to write a wrapper.

**Comment by artmon** [comment]
> You could use https://github.com/XAM-Consulting/SlideOverKit and then you wouldn't need to write a wrapper.

Any example, please
How I can open popup from my ViewModel ?
