### ISSUE TITLE
[iOS] Modal pages do not inherit navbar background color.

### ISSUE THREAD

**Issue by rdaniel0** [rid00z/FreshMvvm#90]
The navbar color in a modal page isn't the same as the page that called it.
![4 1](https://cloud.githubusercontent.com/assets/18712717/17281060/43093224-57dc-11e6-8fe2-31078191786b.png)
![4 2](https://cloud.githubusercontent.com/assets/18712717/17281059/430825f0-57dc-11e6-837b-28349f0d4e33.png)

I understand that when modal is true, you're wrapping the resolved page in a new navigation container.
Is there any way I can get access to that container so I can set the BarBackgroundColor.

Other:
This works as expected in Android

**Comment by rdaniel0** [comment]
Apologies, I just double-checked your documentation and found the following snippet, which I've added my own code to.

`var page = FreshPageModelResolver.ResolvePageModel<ClockOutPageModel>(clockOutData);
var navContainer = new FreshNavigationContainer(page, "ClockOutPage");
navContainer.BarBackgroundColor = Colour.Green;
navContainer.BarTextColor = Color.White;
await CoreMethods.PushNewNavigationServiceModal(navContainer, new FreshBasePageModel[] { page.GetModel() });`

**Comment by rid00z** [comment]
@rdaniel0 You can style the NavigationPage that is shown modally by inheriting from the NavigationContainer and overriding the CreateContainerPage.

**Comment by rdaniel0** [comment]
I finally had some time to test out creating a custom navigation container as you had instructed.
I set the `BarTextColor` and `BarBackgroundColor` in CreateContainerPage override, however when I make an instance of this container and call up a modal page, it still doesn't use the Colors I had set, they're still black text on white bar.

Am I doing something wrong?

`protected override Page CreateContainerPage(Page page)
{
    BarTextColor = Color.White;
    BarBackgroundColor = Color.Green;
    return base.CreateContainerPage(page);
}`

**Comment by marcoseraphin** [comment]
Hi rdanil0,

I have made two classes to change the navigation background and text color.
I mailed with Michael some weeks ago. My classes work as perfect.

You can use them if you want....just rename the inherited classes for your need.

Marco

Class 1:

public class AONNavigationContainer : FreshNavigationContainer
    {
        public AONNavigationContainer(Page page, string navigationPageName) : base(page, navigationPageName)
        {
        }

        protected override Page CreateContainerPage(Page page)
        {
            if (page is NavigationPage || page is MasterDetailPage || page is TabbedPage)
                return page;

            return new AONNavigationPage(page);
        }
    }


Class 2:

public class AONNavigationPage : NavigationPage
    {
        public AONNavigationPage()
        {
        }
        
        /// <summary>
        /// ctor
        /// </summary>
        /// <param name="page">Page.</param>
        public AONNavigationPage(Page page) : base(page)
        {
            // Set BarBackgroundColor to AON Red
            BarTextColor = Color.White;
            BarBackgroundColor = Color.Red;
        }
    }

**Comment by rdaniel0** [comment]
Thank you marcoseraphin! It works perfectly.

**Comment by marcoseraphin** [comment]
rdaniel0....thanx....you are welcome.....I sometimes need some help for my projects...so it is good to give some know how back if needed....
