### ISSUE TITLE
Change method names of ViewIsAppearing and ViewIsDisappearing

### ISSUE THREAD

**Issue by adrianknight89** [rid00z/FreshMvvm#91]
Can we make two changes to the names?

1) If the name represents a question, then it should return a boolean, but the methods return void.
2) Instead of View, use Page since you're using MPPM instead of MVVM.

How about PageAppearing and PageDisappearing?

**Comment by rid00z** [comment]
We could change it but everyone would have a breaking change, not sure it's worth the break change?

**Comment by mzorec** [comment]
You could just obsolete old methods.
