### ISSUE TITLE
what are the use cases of CurrentPage,IsModalAndHasPreviousNavigationStack and PreviousPageModel 

### ISSUE THREAD

**Issue by EmilAlipiev** [rid00z/FreshMvvm#94]
I think these 2 are new in freshmvvm. But what for do we need them? just to display info or breadcrumb or any other purpose? 
 
> /// <summary>
> /// The previous page model, that's automatically filled, on push
> /// </summary>
> public FreshBasePageModel PreviousPageModel { get; set; }
> 
> /// <summary>
> /// A reference to the current page, that's automatically filled, on push
> /// </summary>
> public Page CurrentPage { get; set; }

are they automatically detected when navigating or we must set manually ?

**Comment by rid00z** [comment]
These properties are automatically filled and you shouldn't edit them in a general use.
